ui/src/app/shared/shared.module.ts
this fix error after npm install
ERROR in ./src/app/shared/shared.module.ts
Module not found: Error: Can't resolve 'ng2-charts/ng2-charts' in '[path]/ui/src/app/shared'
=> update ng2-charts include path

io.openems.common/src/io/openems/common/OpenemsConstants.java, io.openems.common/src/io/openems/common/exceptions/CheckedFunction.java, io.openems.common/src/io/openems/common/exceptions/OpenemsError.java, io.openems.common/src/io/openems/common/types/ConfigurationProperty.java, io.openems.common/src/io/openems/common/utils/JsonUtils.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/sunspec/AbstractOpenemsSunspecComponent.java, io.openems.edge.common/src/io/openems/edge/common/type/TypeUtils.java, io.openems.edge.core/bnd.bnd, io.openems.edge.core/src/io/openems/edge/core/host/GetNetworkConfigRequest.java, io.openems.edge.core/src/io/openems/edge/core/host/GetNetworkConfigResponse.java, io.openems.edge.core/src/io/openems/edge/core/host/Host.java, io.openems.edge.core/src/io/openems/edge/core/host/NetworkConfiguration.java, io.openems.edge.core/src/io/openems/edge/core/host/NetworkInterface.java, io.openems.edge.core/src/io/openems/edge/core/host/OperatingSystem.java, io.openems.edge.core/src/io/openems/edge/core/host/OperatingSystemDebianSystemd.java, io.openems.edge.core/src/io/openems/edge/core/host/SetNetworkConfigRequest.java, io.openems.edge.core/src/io/openems/edge/core/host/package-info.java, ui/src/app/app-routing.module.ts, ui/src/app/edge/settings/network/getNetworkConfigRequest.ts, ui/src/app/edge/settings/network/getNetworkConfigResponse.ts, ui/src/app/edge/settings/network/network.component.html, ui/src/app/edge/settings/network/network.component.ts, ui/src/app/edge/settings/network/setNetworkConfigRequest.ts, ui/src/app/edge/settings/network/shared.ts, ui/src/app/edge/settings/settings.component.html, ui/src/app/edge/settings/settings.module.ts
First use case is changing network configuration with a Debian operating system with systemd-networkd backend.
=> New "Host" component for operating system services

.travis.yml, io.openems.backend.b2brest/src/io/openems/backend/b2brest/RestHandler.java, io.openems.backend.b2bwebsocket/src/io/openems/backend/b2bwebsocket/OnRequest.java, io.openems.backend.edgewebsocket.impl/src/io/openems/backend/edgewebsocket/impl/EdgeWebsocketImpl.java, io.openems.backend.uiwebsocket.impl/src/io/openems/backend/uiwebsocket/impl/OnRequest.java, io.openems.edge.common/src/io/openems/edge/common/jsonapi/JsonApi.java, io.openems.edge.controller.api.backend/src/io/openems/edge/controller/api/backend/OnRequest.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/RestHandler.java, io.openems.edge.controller.api.websocket/src/io/openems/edge/controller/api/websocket/OnRequest.java, io.openems.edge.core/src/io/openems/edge/core/host/ExecuteSystemCommandRequest.java, io.openems.edge.core/src/io/openems/edge/core/host/ExecuteSystemCommandResponse.java, io.openems.edge.core/src/io/openems/edge/core/host/Host.java, io.openems.edge.core/src/io/openems/edge/core/host/OperatingSystem.java, io.openems.edge.core/src/io/openems/edge/core/host/OperatingSystemDebianSystemd.java, ui/src/app/app-routing.module.ts, ui/src/app/edge/history/history.component.html, ui/src/app/edge/live/chpsoc/chpsoc.component.html, ui/src/app/edge/settings/settings.component.html, ui/src/app/edge/settings/settings.module.ts, ui/src/app/edge/settings/systemexecute/systemexecute.component.html, ui/src/app/edge/settings/systemexecute/systemexecute.component.ts, ui/src/app/shared/jsonrpc/request/executeCommandRequest.ts, ui/src/app/shared/jsonrpc/response/executeSystemCommandResponse.ts, ui/src/app/shared/translate/cz.ts, ui/src/app/shared/translate/de.ts, ui/src/app/shared/translate/en.ts, ui/src/app/shared/translate/es.ts, ui/src/app/shared/translate/nl.ts
=> Execute system commands via UI

ui/src/app/app.component.html, ui/src/app/edge/live/live.component.html, ui/src/app/edge/live/live.module.ts, ui/src/app/edge/live/offline/offline.component.html, ui/src/app/edge/live/offline/offline.component.ts, ui/src/app/index/index.component.html
Before on IOS:
After on IOS:
Info Text if FEMS offline:
- fix of SideMenu on IOS devices
- if no Grid Value available shows '-'
- add info text if FEMS offline
=> General Adjustments

io.openems.common/src/io/openems/common/exceptions/OpenemsError.java, io.openems.common/src/io/openems/common/utils/JsonUtils.java, io.openems.edge.meter.api/src/io/openems/edge/meter/api/AsymmetricMeter.java, io.openems.edge.meter.discovergy/bnd.bnd, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/DiscovergyApiClient.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/DiscovergyWorker.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/MeterDiscovergy.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/jsonrpc/DiscovergyMeter.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/jsonrpc/Field.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/jsonrpc/GetFieldNamesRequest.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/jsonrpc/GetFieldNamesResponse.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/jsonrpc/GetMetersRequest.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/jsonrpc/GetMetersResponse.java
- Timeout for old meter readings
- Read voltage and grid feed-in energy
- Provide JSON-RPC endpoints
=> Improvements on Discovergy Smart-Meter implementation

ui/src/app/edge/history/autarchy/widget.component.html, ui/src/app/edge/history/history.component.html, ui/src/app/edge/history/selfconsumption/widget.component.html
- enable Autarchy & History Charts for History
=> Add Autarchy & SelfConsumption to History

ui/src/app/edge/history/abstracthistorychart.ts, ui/src/app/edge/history/energy/energy.component.ts, ui/src/app/edge/history/shared.ts, ui/src/app/edge/live/live.component.html
- add second y axis to energymonitor in history for showing soc values
=> Add second y axis to energymonitor in history

ui/src/app/edge/live/live.component.html, ui/src/app/shared/edge/edgeconfig.ts, ui/src/app/shared/type/widget.ts
- fix size of fix digital output widget on mobile devices
=> UI: General Adjustments

ui/src/app/edge/history/history.component.html, ui/src/app/edge/history/history.module.ts, ui/src/app/edge/history/peakshaving/symmetric/chart.component.ts, ui/src/app/edge/history/peakshaving/symmetric/modal/modal.component.html, ui/src/app/edge/history/peakshaving/symmetric/modal/modal.component.ts, ui/src/app/edge/history/peakshaving/symmetric/widget.component.html, ui/src/app/edge/history/peakshaving/symmetric/widget.component.ts, ui/src/app/edge/live/peakshaving/symmetric/modal/modal.component.html, ui/src/app/edge/live/peakshaving/symmetric/symmetricpeakshaving.component.html, ui/src/app/edge/live/peakshaving/symmetric/symmetricpeakshaving.component.ts, ui/src/app/shared/translate/cz.ts, ui/src/app/shared/translate/de.ts, ui/src/app/shared/translate/en.ts, ui/src/app/shared/translate/es.ts, ui/src/app/shared/translate/nl.ts
add symmetric peakshaving chart to history
=> UI: Symmetric Peakshaving Chart

ui/src/app/shared/edge/edge.ts, ui/src/app/shared/pickdate/pickdate.component.ts, ui/src/app/shared/pickdate/popover/popover.component.ts, ui/src/app/shared/service/websocket.ts, ui/src/app/shared/translate/cz.ts, ui/src/app/shared/translate/de.ts, ui/src/app/shared/translate/en.ts, ui/src/app/shared/translate/es.ts, ui/src/app/shared/translate/nl.ts
- when next day or next week is reached pickdate will automatically switch to the next day/week
- no changes to custom dates made
- resubscribe when websocket is reestablished
=> UI:update pickdate period + minor changes

io.openems.edge.ess.sinexcel/src/io/openems/edge/ess/sinexcel/EssSinexcel.java
=> Add Modbus-Slave definition for ESS Sinexcel

ui/src/app/edge/history/consumption/meterchart.component.ts, ui/src/app/edge/history/consumption/modal/modal.component.html, ui/src/app/edge/history/consumption/modal/modal.component.ts, ui/src/app/edge/history/fixdigitaloutput/modal/modal.component.html, ui/src/app/edge/history/fixdigitaloutput/modal/modal.component.ts, ui/src/app/edge/history/fixdigitaloutput/singlechart.component.ts, ui/src/app/edge/history/fixdigitaloutput/totalchart.component.ts, ui/src/app/edge/history/fixdigitaloutput/widget.component.html, ui/src/app/edge/history/fixdigitaloutput/widget.component.ts, ui/src/app/edge/history/history.component.html, ui/src/app/edge/history/history.module.ts, ui/src/app/edge/live/consumption/consumption.component.html
-add metered consumption as history chart
-add fixdigitaloutput component as history chart
=> Gathered UI Adjustments

io.openems.edge.controller.ess.predictivedelaycharge/src/io/openems/edge/controller/ess/predictivedelaycharge/dc/Config.java, io.openems.edge.controller.ess.predictivedelaycharge/src/io/openems/edge/controller/ess/predictivedelaycharge/dc/DcPredictiveDelayCharge.java
Converted String input id to an array to allow multiple charger ids configurable.
=> Multiple charger configurable implementation

io.openems.edge.common/src/io/openems/edge/common/channel/Channel.java, io.openems.edge.timedata.rrd4j/src/io/openems/edge/timedata/rrd4j/RecordWorker.java, io.openems.edge.timedata.rrd4j/src/io/openems/edge/timedata/rrd4j/Rrd4jTimedata.java, io.openems.edge.timedata.rrd4j/src/io/openems/edge/timedata/rrd4j/Rrd4jTimedataImpl.java
- fix local timezone handling
- use rrd4j db pool
- always close() RrdDb files; otherwise the pool fills up and no more files can be opened
- apply coding best practices
- apply Checkstyle
- split interface and impl
=> Improve RRD4j implementation

ui/src/app/app.component.ts, ui/src/app/edge/live/evcs/modal/administration/administration.component.html, ui/src/app/edge/live/evcs/modal/administration/administration.component.ts, ui/src/app/edge/live/evcs/modal/modal.page.html, ui/src/app/edge/live/evcs/modal/modal.page.ts, ui/src/app/edge/live/evcsCluster/modal/evcs-chart/evcs.chart.ts, ui/src/app/edge/live/evcsCluster/modal/evcsCluster-modal.page.ts, ui/src/app/edge/live/live.module.ts, ui/src/app/shared/translate/cz.ts, ui/src/app/shared/translate/de.ts, ui/src/app/shared/translate/en.ts, ui/src/app/shared/translate/es.ts, ui/src/app/shared/translate/nl.ts
remove console.logs
change of EVCS widget logic
add renault zoe button to evcs widget
=> UI: add renault zoe button to evcs widget

io.openems.edge.battery.bmw/src/io/openems/edge/battery/bmw/BmwBatteryImpl.java
=> Start stopable interface in bmw battery

io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/symmetric/ChannelHandler.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/symmetric/GenericManagedSymmetricEssImpl.java
Fix allowedChargeDischargeCallback in ChannelHandler and add PowerConstraints if ess generic is not STARTED
=> Ess generic constraints

io.openems.edge.batteryinverter.api/src/io/openems/edge/batteryinverter/api/SymmetricBatteryInverter.java, io.openems.edge.batteryinverter.kaco.blueplanetgridsave/src/io/openems/edge/batteryinverter/kaco/blueplanetgridsave/KacoBlueplanetGridsaveImpl.java, io.openems.edge.batteryinverter.refu88k/src/io/openems/edge/batteryinverter/refu88k/RefuStore88kImpl.java, io.openems.edge.common/src/io/openems/edge/common/startstop/StartStoppable.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/symmetric/ChannelHandler.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/symmetric/GenericManagedSymmetricEss.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/symmetric/GenericManagedSymmetricEssImpl.java
1. Slave table is added to the Generic Ess
2. Changed the Active_charge_energy channel and Active_Discharge_energy channel for battery inverter Kaco and Refu.
=> Modbus slave table for the Generic Ess 

ui/src/app/edge/history/abstracthistorychart.ts, ui/src/app/edge/history/autarchy/widget.component.html, ui/src/app/edge/history/autarchy/widget.component.ts, ui/src/app/edge/history/consumption/widget.component.html, ui/src/app/edge/history/consumption/widget.component.ts, ui/src/app/edge/history/energy/energy.component.ts, ui/src/app/edge/history/grid/widget.component.ts, ui/src/app/edge/history/production/widget.component.ts, ui/src/app/edge/history/selfconsumption/widget.component.html, ui/src/app/edge/history/selfconsumption/widget.component.ts, ui/src/app/edge/history/storage/widget.component.ts, ui/src/app/shared/edge/currentdata.ts
- Hotfix for kWh-Value Chart to show regular data if no kWh data is available
=> UI: History Chartfix

io.openems.edge.meter.sma.shm20/src/io/openems/edge/meter/sma/shm20/MeterSmaShm20Impl.java
I have fixed the misunderstanding of PRODUCTION and CONSUMPTION in the SMA SHM 2.0 Meter Implementation
=> Meter SMA SHM 2.0: Fixed misunderstanding of PRODUCTION/CONSUMPTION

io.openems.edge.application/EdgeApp.bndrun, io.openems.edge.simulator/src/io/openems/edge/simulator/app/SimulatorApp.java, io.openems.edge.simulator/src/io/openems/edge/simulator/datasource/api/AbstractCsvDatasource.java, io.openems.edge.simulator/src/io/openems/edge/simulator/datasource/api/SimulatorDatasource.java, io.openems.edge.simulator/src/io/openems/edge/simulator/evcs/SimulatedEvcs.java, io.openems.edge.simulator/src/io/openems/edge/simulator/meter/grid/acting/GridMeter.java, io.openems.edge.simulator/src/io/openems/edge/simulator/meter/nrc/acting/NrcMeter.java, io.openems.edge.simulator/src/io/openems/edge/simulator/meter/production/acting/ProductionMeter.java, io.openems.edge.simulator/src/io/openems/edge/simulator/pvinverter/PvInverter.java
- First: tries the full Channel-Address ("Component-ID/Channel-ID")
- Second tries only the Channel-ID
=> Improve handling of Simulator Datasources

io.openems.edge.batteryinverter.kaco.blueplanetgridsave/src/io/openems/edge/batteryinverter/kaco/blueplanetgridsave/Config.java, io.openems.edge.batteryinverter.kaco.blueplanetgridsave/src/io/openems/edge/batteryinverter/kaco/blueplanetgridsave/KacoBlueplanetGridsaveImpl.java, io.openems.edge.batteryinverter.kaco.blueplanetgridsave/test/io/openems/edge/batteryinverter/kaco/blueplanetgridsave/KacoBlueplanetGridsaveTest.java, io.openems.edge.batteryinverter.kaco.blueplanetgridsave/test/io/openems/edge/batteryinverter/kaco/blueplanetgridsave/MyConfig.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/sunspec/AbstractOpenemsSunSpecComponent.java, io.openems.edge.common/src/io/openems/edge/common/sum/Sum.java, io.openems.edge.core/src/io/openems/edge/core/sum/SumImpl.java, io.openems.edge.ess.cluster/src/io/openems/edge/ess/cluster/EssCluster.java
1. kaco 92
- added a activate channel in config.
- added the check for 92 model reading
2. _sum
- added the allowed charge and discharge power on sumImpl
- and Reactive power channel
=> kaco92_and_sum_update

io.openems.edge.bridge.onewire/src/com/dalsemi/onewire/adapter/UPacketBuilder.java, io.openems.edge.bridge.onewire/src/com/dalsemi/onewire/utils/Convert.java, io.openems.edge.bridge.onewire/src/com/dalsemi/onewire/utils/OWPath.java
Found via `codespell v2.0.dev`
=> Fix typo variable 'delimeter' + misc fixes

io.openems.edge.controller.ess.predictivedelaycharge/src/io/openems/edge/controller/ess/predictivedelaycharge/AbstractPredictiveDelayCharge.java
Correcting the storing of variables which were wrongly done for debugging purpose in the last merge
=> correct the references for Self-Consumption controller

io.openems.edge.bridge.onewire/src/com/dalsemi/onewire/adapter/DSPortAdapter.java, io.openems.edge.bridge.onewire/src/com/dalsemi/onewire/adapter/LSerialAdapter.java, io.openems.edge.bridge.onewire/src/com/dalsemi/onewire/adapter/NetAdapter.java, io.openems.edge.bridge.onewire/src/com/dalsemi/onewire/adapter/TMEXAdapter.java, io.openems.edge.bridge.onewire/src/com/dalsemi/onewire/adapter/UPacketBuilder.java, io.openems.edge.bridge.onewire/src/com/dalsemi/onewire/adapter/USerialAdapter.java, io.openems.edge.controller.ess.onefullcycle/readme.adoc
Found via `codespell v2.0.dev`
=> Fix various typos

io.openems.edge.goodwe/src/io/openems/edge/goodwe/ess/Config.java, io.openems.edge.goodwe/src/io/openems/edge/goodwe/ess/GoodWeEss.java, io.openems.edge.goodwe/src/io/openems/edge/goodwe/ess/GoodWeEssImpl.java, io.openems.edge.goodwe/test/io/openems/edge/goodwe/ess/GoodWeEtBatteryInverterImplTest.java, io.openems.edge.goodwe/test/io/openems/edge/goodwe/ess/MyConfig.java
- fix identification of GoodWe battery inverter if there was no modbus connection initially
- fix nullpointerexception due to late setting of 'this.config'
=> GoodWe fixes

io.openems.edge.ess.mr.gridcon/src/io/openems/edge/ess/mr/gridcon/enums/ErrorCodeChannelId1.java, io.openems.edge.ess.refu/src/io/openems/edge/ess/refu/ErrorHandler.java, io.openems.edge.simulator/src/io/openems/edge/simulator/CsvUtils.java, io.openems.edge.simulator/src/io/openems/edge/simulator/datasource/csv/predefined/CsvDatasourcePredefined.java
Found via `codespell v2.1.dev0`
=> Fix various source typos

ui/src/app/edge/live/heatpump/modal/modal.component.html, ui/src/app/shared/chartoptions/popover/popover.component.html
* fixes ion-toggle click problem
=> UI: ion-toggle fix

ui/src/app/app-routing.module.ts, ui/src/app/edge/history/history.component.html, ui/src/app/edge/history/history.module.ts, ui/src/app/edge/history/peakshaving/timeslot/chart.component.ts, ui/src/app/edge/history/peakshaving/timeslot/timeslotpeakshavingchartoverview/timeslotpeakshavingchartoverview.component.html, ui/src/app/edge/history/peakshaving/timeslot/timeslotpeakshavingchartoverview/timeslotpeakshavingchartoverview.component.ts, ui/src/app/edge/history/peakshaving/timeslot/widget.component.html, ui/src/app/edge/history/peakshaving/timeslot/widget.component.ts, ui/src/app/edge/live/heatingelement/modal/modal.component.ts, ui/src/app/edge/live/heatpump/modal/modal.component.ts, ui/src/app/edge/live/live.component.html, ui/src/app/edge/live/live.module.ts, ui/src/app/edge/live/peakshaving/asymmetric/modal/modal.component.ts, ui/src/app/edge/live/peakshaving/symmetric/modal/modal.component.ts, ui/src/app/edge/live/peakshaving/timeslot/modal/modal.component.html, ui/src/app/edge/live/peakshaving/timeslot/modal/modal.component.ts, ui/src/app/edge/live/peakshaving/timeslot/timeslotpeakshaving.component.html, ui/src/app/edge/live/peakshaving/timeslot/timeslotpeakshaving.component.ts, ui/src/app/edge/live/singlethreshold/modal/modal.component.ts, ui/src/app/edge/settings/channels/channels.component.html, ui/src/app/edge/settings/channels/channels.component.ts, ui/src/app/shared/translate/cz.ts, ui/src/app/shared/translate/de.ts, ui/src/app/shared/translate/en.ts, ui/src/app/shared/translate/es.ts, ui/src/app/shared/translate/fr.ts, ui/src/app/shared/translate/nl.ts, ui/src/app/shared/type/widget.ts, ui/src/theme/variables.scss
=> UI: TimeslotPeakshaving Live + History Widget

doc/modules/ROOT/pages/gettingstarted.adoc, doc/modules/ROOT/pages/i18n/de.po, doc/modules/ROOT/pages/i18n/translate.pot, doc/modules/ROOT/pages/introduction.adoc
These are some minor improvements and fixes I made while reading the documentation.
=> Various documentation improvements and fixes

ui/src/app/edge/history/consumption/consumptionchartoverview/consumptionchartoverview.component.ts, ui/src/app/edge/history/consumption/totalchart.component.ts, ui/src/app/edge/history/consumption/widget.component.html, ui/src/app/edge/history/consumption/widget.component.ts, ui/src/app/edge/live/selfconsumption/selfconsumption.component.ts
- add metered consumption to total consumption chart
- remove console.logs
=> UI: History add metered consumption to total consumption chart

io.openems.edge.controller.api.rest/readme.adoc, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/AbstractRestApi.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/RestHandler.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/readonly/Config.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/readonly/RestApiReadOnlyImpl.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/readwrite/Config.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/readwrite/RestApiReadWriteImpl.java, io.openems.edge.meter.sma.shm20/src/io/openems/edge/meter/sma/shm20/MeterSmaShm20Impl.java
- Made connection limit configurable
- Made channel output in GET requests more comprehensive and inline with EdgeConfig
- Deliver the approriate response code for authentication errors
- Enable multiple-at-once channel readings as a JSON Array
=> Several improvements in the REST API

ui/src/app/edge/history/consumption/widget.component.html, ui/src/app/edge/history/consumption/widget.component.ts
- show correct energy values for other consumption
=> UI: Historiy Consumption Fix

io.openems.edge.battery.soltaro/src/io/openems/edge/battery/soltaro/single/versionc/SingleRackVersionCImpl.java
Replaces dummy characteristic of Soltaro C by the correct one.
=> Replaces dummy characteristic

io.openems.edge.battery.bmw/src/io/openems/edge/battery/bmw/BmwBatteryImpl.java
=> Missed "throws exception"

io.openems.edge.battery.api/doc/forcecharge-statemachine.md, io.openems.edge.battery.api/src/io/openems/edge/battery/protection/force/ForceCharge.java, io.openems.edge.battery.api/src/io/openems/edge/battery/protection/force/ForceDischarge.java, io.openems.edge.battery.api/test/io/openems/edge/battery/protection/BatteryProtectionTest.java
- add link from Block to Force states
- add statemachine diagram for documentation
=> Battery-Protection: Fix Force-Charge/-Discharge in Block-State

io.openems.backend.application/src/io/openems/backend/application/BackendApp.java, io.openems.edge.controller.api.common/src/io/openems/edge/controller/api/common/Utils.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/ComponentManagerImpl.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/DefaultConfigurationWorker.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/EdgeConfigWorker.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/OsgiValidateWorker.java
Config.getProperties() can be null
=> ConfigurationAdmin: avoid NullPointerException

io.openems.edge.simulator/src/io/openems/edge/simulator/ess/symmetric/reacting/EssSymmetric.java
Improved the Soc calculation by using the double value instead of float and estimating the soc through the current energy value in the battery.
=> SoC estimation improvement in simulator.

io.openems.edge.evcs.goe.chargerhome/.project, io.openems.edge.evcs.goe.chargerhome/src/io/openems/edge/evcs/goe/chargerhome/GoeChargerHomeImpl.java
Solved the issue https://github.com/OpenEMS/openems/issues/1580#issue-958815534
=> Fixed the minimum and maximum hardware  power calculation

io.openems.edge.controller.api/src/io/openems/edge/controller/test/DummyController.java, io.openems.edge.controller.debug.log/src/io/openems/edge/controller/debuglog/Config.java, io.openems.edge.controller.debug.log/src/io/openems/edge/controller/debuglog/DebugLogImpl.java, io.openems.edge.controller.debug.log/test/io/openems/edge/controller/debuglog/DebugLogImplTest.java, io.openems.edge.controller.debug.log/test/io/openems/edge/controller/debuglog/MyConfig.java
+ Implement @Modified to apply changed configuration faster
=> DebugLogController: add config setting to print Component Alias

io.openems.edge.timedata.influxdb/src/io/openems/edge/timedata/influxdb/InfluxTimedataImpl.java
The timestamp is rounded to the global configured Cycle-Time
=> InfluxDB: write data with milliseconds precision

io.openems.edge.controller.ess.limittotaldischarge/src/io/openems/edge/controller/ess/limittotaldischarge/Config.java, io.openems.edge.controller.ess.limittotaldischarge/src/io/openems/edge/controller/ess/limittotaldischarge/LimitTotalDischargeController.java, io.openems.edge.controller.ess.limittotaldischarge/src/io/openems/edge/controller/ess/limittotaldischarge/LimitTotalDischargeControllerImpl.java, io.openems.edge.controller.ess.limittotaldischarge/src/io/openems/edge/controller/ess/limittotaldischarge/State.java, io.openems.edge.controller.ess.limittotaldischarge/test/io/openems/edge/controller/ess/limittotaldischarge/LimitTotalDischargeControllerTest.java, io.openems.edge.controller.ess.timeofusetariff.discharge/src/io/openems/edge/controller/ess/timeofusetariff/discharge/TimeOfUseTariffDischargeImpl.java
Set active power for both AC and DC systems were the same, and it is changed now by recognizing if it is a DC or AC system and giving separate set points.
1. Controller implementation is split into Interface and implementation.
2. Reference for limit total discharge and emergency capacity reserves is updated with target filters.
=> Bug-Fix/Time-Of-Use Tariff Discharge controller

io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/odoo/OdooHandler.java, io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/odoo/OdooUtils.java
Co-authored-by: Maximilian Lang <35968713+mlang97@users.noreply.github.com>
=> Odoo: store and authenticate username/email in lower case (#209)

io.openems.edge.application/EdgeApp.bndrun, io.openems.edge.battery.fenecon.home/src/io/openems/edge/battery/fenecon/home/FeneconHomeBatteryImpl.java
Co-authored-by: huseyin sahutoglu <hueseyin.sahutoglu@fenecon.de>
=> FENECON Home Battery: add Component deactivate

cnf/pom.xml, io.openems.shared.influxdb/src/io/openems/shared/influxdb/InfluxConnector.java, io.openems.wrapper/bnd.bnd, io.openems.wrapper/influxdb-client.bnd, io.openems.wrapper/retrofit2.bnd
Co-authored-by: Maximilian Lang <35968713+mlang97@users.noreply.github.com>
=> Update InfluxDB dependencies

io.openems.backend.edgewebsocket/src/io/openems/backend/edgewebsocket/EdgeWebsocketImpl.java, io.openems.backend.timedata.influx/src/io/openems/backend/timedata/influx/FieldTypeConflictHandler.java, io.openems.backend.timedata.influx/src/io/openems/backend/timedata/influx/Influx.java, io.openems.backend.uiwebsocket/src/io/openems/backend/uiwebsocket/impl/UiWebsocketImpl.java, io.openems.common/src/io/openems/common/jsonrpc/request/QueryHistoricTimeseriesDataRequest.java, io.openems.common/src/io/openems/common/jsonrpc/request/QueryHistoricTimeseriesEnergyPerPeriodRequest.java, io.openems.common/src/io/openems/common/jsonrpc/request/QueryHistoricTimeseriesEnergyRequest.java, io.openems.common/src/io/openems/common/utils/JsonUtils.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/symmetric/statemachine/ErrorHandler.java, io.openems.edge.fenecon.mini/src/io/openems/edge/fenecon/mini/ess/FeneconMiniEss.java, io.openems.edge.timedata.influxdb/src/io/openems/edge/timedata/influxdb/InfluxTimedataImpl.java, io.openems.shared.influxdb/bnd.bnd, io.openems.shared.influxdb/src/io/openems/shared/influxdb/InfluxConnector.java, io.openems.wrapper/influxdb-client.bnd
- Bugfix for InfluxDB v2 implementation:
- add missing runtime dependencies
- use ThreadPool for InfluxDB batch writes
- improve exception handling
- Add continuous debug output to Ui.Websocket and Edge.Websocket
- Add fallback for Resolution and Timezone for older UI versions
- Improvement on Generic.Ess ErrorHandler
=> FEMS-Backports for 2022.04

io.openems.backend.timedata.influx/src/io/openems/backend/timedata/influx/Config.java, io.openems.backend.timedata.influx/src/io/openems/backend/timedata/influx/Influx.java, io.openems.edge.timedata.influxdb/src/io/openems/edge/timedata/influxdb/Config.java, io.openems.edge.timedata.influxdb/src/io/openems/edge/timedata/influxdb/InfluxTimedataImpl.java, io.openems.shared.influxdb/src/io/openems/shared/influxdb/InfluxConnector.java
@sfeilmeier I reworked the Config for InfluxDB. This allows users to connect their Backend to InfluxCloud (with https). You can still connect to classic instances by entering an appropriate URL with protocol, ip & port and setting username:password as apikey.
=> reworked Config and Influx to be compatible with InfluxDBv2

io.openems.edge.batteryinverter.api/src/io/openems/edge/batteryinverter/api/OffGridBatteryInverter.java, io.openems.edge.batteryinverter.sinexcel/src/io/openems/edge/batteryinverter/sinexcel/Sinexcel.java, io.openems.edge.batteryinverter.sinexcel/src/io/openems/edge/batteryinverter/sinexcel/SinexcelImpl.java, io.openems.edge.batteryinverter.sinexcel/src/io/openems/edge/batteryinverter/sinexcel/statemachine/ErrorHandler.java, io.openems.edge.batteryinverter.sinexcel/src/io/openems/edge/batteryinverter/sinexcel/statemachine/GoRunningHandler.java, io.openems.edge.batteryinverter.sinexcel/src/io/openems/edge/batteryinverter/sinexcel/statemachine/GoStoppedHandler.java, io.openems.edge.batteryinverter.sinexcel/src/io/openems/edge/batteryinverter/sinexcel/statemachine/RunningHandler.java, io.openems.edge.common/src/io/openems/edge/common/channel/BooleanDoc.java, io.openems.edge.common/src/io/openems/edge/common/channel/BooleanReadChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/StateChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/StateChannelDoc.java
This fixes read problems with Sinexcel Battery Inverters.
Also: move debounce feature from StateChannel to all BooleanChannels
=> Sinexcel Battery-Inverter: add debounce for channels

ui/src/app/edge/history/consumption/meterchart.component.ts, ui/src/app/edge/history/consumption/otherchart.component.ts, ui/src/app/edge/history/consumption/singlechart.component.ts, ui/src/app/edge/history/consumption/totalchart.component.ts, ui/src/app/edge/history/consumption/widget.component.html, ui/src/app/edge/history/consumption/widget.component.ts, ui/src/app/edge/history/production/totalchart.ts, ui/src/app/edge/live/production/production.component.html, ui/src/app/shared/service/utils.ts
Fixed not displayed meters and wrong displaying of labels in history/consumptionchartOverview
=> UI: fix not displayed meters

io.openems.common/src/io/openems/common/jsonrpc/response/AuthenticateResponse.java, io.openems.edge.controller.api.websocket/src/io/openems/edge/controller/api/websocket/OnRequest.java
Co-authored-by: Michael Grill <59126309+michaelgrill@users.noreply.github.com>
=> Fix Language NullPointerException in Websocket.Api

io.openems.edge.batteryinverter.sinexcel/bnd.bnd, io.openems.edge.batteryinverter.sinexcel/src/io/openems/edge/batteryinverter/sinexcel/Sinexcel.java, io.openems.edge.batteryinverter.sinexcel/src/io/openems/edge/batteryinverter/sinexcel/SinexcelImpl.java
Seems the original values from modbus are not reliable; tested on fems
Also: change DC_(DIS)CHARGE_ENERGY to LONG to avoid 'is not fitting in Integer range' exception
=> Sinexcel: calculate Energy from ActivePower

cnf/pom.xml, io.openems.backend.application/BackendApp.bndrun, io.openems.edge.application/EdgeApp.bndrun
The update in #1831 causes empty component configuration window
=> Downgrade Apache Felix Web Console

io.openems.edge.core/src/io/openems/edge/app/api/RestJsonApiReadWrite.java, io.openems.edge.core/src/io/openems/edge/app/integratedsystem/FeneconHome.java, io.openems.edge.core/src/io/openems/edge/app/pvinverter/FroniusPvInverter.java, io.openems.edge.core/src/io/openems/edge/app/pvinverter/KostalPvInverter.java, io.openems.edge.core/src/io/openems/edge/app/pvinverter/SmaPvInverter.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/AppDescriptor.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/dependency/AppManagerAppHelperImpl.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/translation_de.properties, io.openems.edge.core/src/io/openems/edge/core/appmanager/translation_en.properties
App Manager changes:
Bugfix: setting app as dependency with specific instanceid without properties
Added Fronius PvInverter
=> App Manager

io.openems.common/src/io/openems/common/websocket/AbstractWebsocketServer.java, io.openems.edge.application/EdgeApp.bndrun, io.openems.edge.meter.bgetech/.classpath, io.openems.edge.meter.bgetech/bnd.bnd, io.openems.edge.meter.bgetech/generated/buildfiles, io.openems.edge.meter.bgetech/readme.adoc, io.openems.edge.meter.bgetech/src/io/openems/edge/meter/bgetech/Config.java, io.openems.edge.meter.bgetech/src/io/openems/edge/meter/bgetech/MeterBgeTechDrt428M2.java, io.openems.edge.meter.bgetech/src/io/openems/edge/meter/bgetech/MeterBgeTechDrt428M2Impl.java
Edited the meter, from the review comments.
1. bndrun file is alphabetically sorted.
2. readme.adoc file edited, and bnd file for the meter has proper bundle-name now
3. Changes in the meter Impl file
- typos edited,
- impl implements the interface now.
- scope for the activate method
=> Changes to the BGE tech meter

cnf/pom.xml, io.openems.edge.evcs.ocpp.server/src/io/openems/edge/evcs/ocpp/server/MyJsonServer.java, io.openems.wrapper/bnd.bnd, io.openems.wrapper/eu.chargetime.ocpp.bnd
- Update dependencies
- Add Exception package to Bundle-Export
- Implement 'authenticateSession' method (to be checked...)
As discussed here: https://community.openems.io/t/error-in-ocpp-server-component/1028
=> OCPP-Server fix

build.gradle, settings.gradle
* include directories with build.gradle
* modified to work also with non bnd subprojects
=> Fix Gradle buildAntoraDocs

io.openems.backend.alerting/src/io/openems/backend/alerting/Alerting.java, io.openems.backend.alerting/src/io/openems/backend/alerting/Handler.java, io.openems.backend.alerting/src/io/openems/backend/alerting/Message.java, io.openems.backend.alerting/src/io/openems/backend/alerting/handler/OfflineEdgeHandler.java, io.openems.backend.alerting/src/io/openems/backend/alerting/message/OfflineEdgeMessage.java, io.openems.backend.alerting/src/io/openems/backend/alerting/scheduler/MessageScheduler.java, io.openems.backend.alerting/src/io/openems/backend/alerting/scheduler/MinuteTimer.java, io.openems.backend.alerting/src/io/openems/backend/alerting/scheduler/Scheduler.java, io.openems.backend.alerting/test/io/openems/backend/alerting/AlertingTest.java, io.openems.backend.alerting/test/io/openems/backend/alerting/handler/TestOfflineEdgeHandler.java, io.openems.backend.alerting/test/io/openems/backend/alerting/scheduler/SchedulerTest.java, io.openems.backend.common/src/io/openems/backend/common/metadata/Edge.java, io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/OdooMetadata.java, io.openems.common/src/io/openems/common/event/EventReader.java, io.openems.edge.application/EdgeApp.bndrun
- Add Executor with one Thread
- Handle Events in Queue
- Check validity again just before sending an alert (when queue is very long)
- Fix typos/naming
=> Backend Alerting: bugfixes and improvements

io.openems.edge.evcs.core/readme.adoc
Add manual for implementing an evcs
=> EVCS: Add manual for implementing an evcs

io.openems.edge.meter.kdk/readme.adoc, io.openems.edge.meter.kdk/src/io/openems/edge/meter/kdk/puct2/Config.java, io.openems.edge.meter.kdk/src/io/openems/edge/meter/kdk/puct2/MeterKdk2puctImpl.java, io.openems.edge.meter.kdk/test/io/openems/edge/meter/kdk/puct2/MyConfig.java
- Rename `meterType` configuration parameter to be compatible with OpenEMS UI
- Fix Consumption/Production Energy
=> KDK Meter: backport updates from FEMS

.gitpod.Dockerfile, .gitpod.yml
Use latest Odoo module from https://github.com/OpenEMS/odoo-openems/tree/15.0
=> Update to Odoo 15

io.openems.edge.pvinverter.solarlog/bnd.bnd, io.openems.edge.pvinverter.solarlog/src/io/openems/edge/pvinverter/solarlog/SolarLogImpl.java
Production energy for Solar-Log was not cumulated
Co-authored-by: Maximilian Lang <maximilian.lang@fenecon.de>
=> Solar-Log PV-Inverter: cumulate production energy (#628)

io.openems.edge.battery.api/src/io/openems/edge/battery/protection/BatteryProtection.java
Changing the units in the Battery protection channels.
=> Changing the units, Battery protection

io.openems.edge.predictor.persistencemodel/readme.adoc
Changed broken URL from holtwinters to persistencemodel
=> fix for broken URL in readme.adoc

ui/src/app/edge/history/channelthreshold/channelthresholdchartoverview/channelthresholdchartoverview.component.html, ui/src/app/edge/history/chpsoc/chpsocchartoverview/chpsocchartoverview.component.html, ui/src/app/edge/history/common/production/chart/totalAcChart.ts, ui/src/app/edge/history/common/production/chart/totalChart.ts, ui/src/app/edge/history/common/production/overview/overview.html, ui/src/app/edge/history/consumption/consumptionchartoverview/consumptionchartoverview.component.html, ui/src/app/edge/history/delayedselltogrid/symmetricpeakshavingchartoverview/delayedselltogridchartoverview.component.html, ui/src/app/edge/history/fixdigitaloutput/fixdigitaloutputchartoverview/fixdigitaloutputchartoverview.component.html, ui/src/app/edge/history/grid/gridchartoverview/gridchartoverview.component.html, ui/src/app/edge/history/gridoptimizedcharge/gridoptimizedchargechartoverview/gridoptimizedchargechartoverview.component.html, ui/src/app/edge/history/heatingelement/heatingelementchartoverview/heatingelementchartoverview.component.html, ui/src/app/edge/history/heatpump/heatpumpchartoverview/heatpumpchartoverview.component.html, ui/src/app/edge/history/peakshaving/asymmetric/asymmetricpeakshavingchartoverview/asymmetricpeakshavingchartoverview.component.html, ui/src/app/edge/history/peakshaving/symmetric/symmetricpeakshavingchartoverview/symmetricpeakshavingchartoverview.component.html, ui/src/app/edge/history/peakshaving/timeslot/timeslotpeakshavingchartoverview/timeslotpeakshavingchartoverview.component.html, ui/src/app/edge/history/selfconsumption/selfconsumptionchartoverview/selfconsumptionchartoverview.component.html, ui/src/app/edge/history/singlethreshold/singlethresholdchartoverview/singlethresholdchartoverview.component.html, ui/src/app/edge/history/storage/storagechartoverview/storagechartoverview.component.html, ui/src/app/edge/history/timeofusetariffdischarge/timeofusetariffdischargeoverview/timeofusetariffdischargechartoverview.component.html
- lost null check on PR
- remove old channels, that slow the history, because old database gets called
- translation key "General.total" was refactored to "General.TOTAL"
- fix Runtime error due to refactoring of historyPeriod to be a Observable and not doing all the changes necessary
Co-authored-by: Lukas Rieger <lukas.rieger@fenecon.de>
=> UI: Fix Bugs

io.openems.edge.controller.channelthreshold/bnd.bnd, io.openems.edge.controller.channelthreshold/src/io/openems/edge/controller/channelthreshold/ControllerChannelThreshold.java, io.openems.edge.controller.channelthreshold/src/io/openems/edge/controller/channelthreshold/ControllerChannelThresholdImpl.java, io.openems.edge.controller.chp.soc/bnd.bnd, io.openems.edge.controller.chp.soc/src/io/openems/edge/controller/chp/soc/ControllerChpSoc.java, io.openems.edge.controller.chp.soc/src/io/openems/edge/controller/chp/soc/ControllerChpSocImpl.java, io.openems.edge.controller.ess.fixactivepower/bnd.bnd, io.openems.edge.controller.ess.fixactivepower/src/io/openems/edge/controller/ess/fixactivepower/ControllerEssFixActivePower.java, io.openems.edge.controller.ess.fixactivepower/src/io/openems/edge/controller/ess/fixactivepower/ControllerEssFixActivePowerImpl.java, io.openems.edge.controller.io.channelsinglethreshold/bnd.bnd, io.openems.edge.controller.io.channelsinglethreshold/src/io/openems/edge/controller/io/channelsinglethreshold/ControllerIoChannelSingleThreshold.java, io.openems.edge.controller.io.channelsinglethreshold/src/io/openems/edge/controller/io/channelsinglethreshold/ControllerIoChannelSingleThresholdImpl.java, io.openems.edge.controller.io.fixdigitaloutput/bnd.bnd, io.openems.edge.controller.io.fixdigitaloutput/src/io/openems/edge/controller/io/fixdigitaloutput/ControllerIoFixDigitalOutput.java, io.openems.edge.controller.io.fixdigitaloutput/src/io/openems/edge/controller/io/fixdigitaloutput/ControllerIoFixDigitalOutputImpl.java
Co-authored-by: Sagar Venu <32655208+venu-sagar@users.noreply.github.com>
=> Add 'CumulatedActiveTime' Channel for Controllers with Relay (#677)

cnf/checkstyle.xml, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/pvinverter/KacoBlueplanetHybrid10PvInverterImpl.java
...to improve compatibility with `ElectricityMeter` (see #2144)
=> KACO10 PV-Inverter: add phase values

ui/src/assets/i18n/de.json
General typo fixes to display in UI.
=> UI: General Typo fixes

io.openems.common/src/io/openems/common/channel/PersistencePriority.java, io.openems.common/src/io/openems/common/function/ThrowingTriConsumer.java, io.openems.common/src/io/openems/common/jsonrpc/notification/AbstractDataNotification.java, io.openems.common/src/io/openems/common/jsonrpc/notification/AggregatedDataNotification.java, io.openems.common/src/io/openems/common/jsonrpc/notification/ResendDataNotification.java, io.openems.common/src/io/openems/common/jsonrpc/notification/TimestampedDataNotification.java, io.openems.common/src/io/openems/common/timedata/DurationUnit.java, io.openems.common/src/io/openems/common/utils/CollectorUtils.java, io.openems.common/src/io/openems/common/utils/JsonUtils.java
Split TimestampedDataNotification into 
* TimestampedDataNotification
* AggregatedDataNotification
* ResendDataNotification
Added/enhanced some utilities classes. This PR is one in a series to provide highly scalable database access for OpenEMS.
=> Split DataNotification into Timestamped-, Aggregated- and ResendDataNotification.

doc/modules/ROOT/pages/backend/backend-to-backend.adoc
Du stop the subscription --> To stop the subscription
=> Docs: Fix typing error in backend-to-backend section

ui/.vscode/settings.json
Reduce RAM Usage with Filewatcher Rules
https://stackoverflow.com/questions/53658769/why-does-vs-code-require-so-much-memory-how-can-i-make-it-run-more-memory-effic
=> UI: Reduce RAM usage in VSC

ui/src/app/edge/history/common/energy/flat/flat.html, ui/src/app/edge/history/common/energy/flat/flat.ts
* Fix EnergyMonitor being too small in width on mobile devices
* Hide ion-card on mobile devices to create more space
=> UI: adjust energymonitor for mobile devices

ui/src/app/edge/history/timeofusetariffdischarge/chart.component.ts, ui/src/app/edge/history/timeofusetariffdischarge/widget.component.ts
->  Removed unused channels.
->  Made channels to subscribe based on factory id.
=> Time-of-Use Tariff Controller UI: remove unused channel subscription

io.openems.edge.meter.janitza/src/io/openems/edge/meter/janitza/umg511/MeterJanitzaUmg511Impl.java
removed duplicated modbus slave table entry for ElectricityMeter
=> MeterJanitzaUmg511: removed duplicated entry in modbus slave table

io.openems.edge.common/src/io/openems/edge/common/test/TestUtils.java, io.openems.edge.meter.api/src/io/openems/edge/meter/api/ElectricityMeter.java, io.openems.edge.meter.api/src/io/openems/edge/meter/api/SinglePhaseMeter.java, io.openems.edge.meter.api/src/io/openems/edge/meter/test/AbstractDummyElectricityMeter.java, io.openems.edge.meter.api/src/io/openems/edge/meter/test/DummyElectricityMeter.java, io.openems.edge.meter.api/src/io/openems/edge/meter/test/DummySinglePhaseElectricityMeter.java, io.openems.edge.meter.api/test/io/openems/edge/meter/api/ElectricityMeterTest.java, io.openems.edge.meter.api/test/io/openems/edge/meter/api/SinglePhaseMeterTest.java
Fixed (presumably) Copy-paste error.
=> Bugfix in SinglePhaseMeter.calculateSinglePhaseFromActivePower

io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/odoo/Domain.java, io.openems.backend.metadata.odoo/test/io/openems/backend/metadata/odoo/odoo/DomainTest.java
This is one of many prepare PRs / commits for a bigger PR: SumStateAlert #2260
=> Backend: MetadataOdoo: Added hashcode to domain and changed equals method a bit, added Test for Domain

io.openems.common/src/io/openems/common/utils/JsonUtils.java
This commits refactors the generation of JsonArrays in the JsonUtils class in io.openems.common.utils.
=> Common: Utils - Refactor of JsonUtils - JsonArray build

io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/odoo/OdooUtils.java, io.openems.backend.metadata.odoo/test/io/openems/backend/metadata/odoo/odoo/OdooUtilsTest.java
=> Backend: MetadataOdoo: OdooUtils enhancement -> getRawValue and isUnset method

io.openems.common/src/io/openems/common/event/EventBuilder.java, io.openems.common/src/io/openems/common/event/EventReader.java
* EventBuilder received a Build method for new Events and
* EventReader received toString, hashCode and equals method
=> Common: Eventbuilder received build method and EventReader received toString + hashCode + equals method

io.openems.common/src/io/openems/common/test/TimeLeapClock.java
This commit adds a constructor, with an Instant Option.
=> Common: TimeLeapClock constructor with Instant, and "now" method

io.openems.edge.common/src/io/openems/edge/common/channel/internal/AbstractReadChannel.java, io.openems.edge.controller.api.rest/test/io/openems/edge/controller/api/rest/readwrite/ControllerApiRestReadWriteImplTest.java, io.openems.edge.meter.api/src/io/openems/edge/meter/test/AbstractDummyElectricityMeter.java
=> JUnit Test Framework: unify Dummy components

io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/odoo/OdooHandler.java, io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/odoo/OdooUtils.java
The Odoo Chatter implementation is not working.
As it is currentrly also not used, i would suggest removing it.
What is your opinion @sfeilmeier ?
=> remove `addChatterMessage` from OdooUtils and OdooHandler

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/release.yml, build.gradle, gradle.properties
This will update the Workflows to use Java 21, while still building with Java 17 compatibility
=> Update Workflows to use JDK 21

.github/workflows/build.yml, .github/workflows/release.yml
- fix UI-Codecov
- fix Release UI-Artifact
- remove duplicate `npm install`
- improve java-build readability
=> Update build actions

.gradle-wrapper/gradle-wrapper.properties, gradlew
`./gradlew wrapper --gradle-version=8.9`
=> Update Gradle to 8.9

doc/modules/ROOT/pages/edge/implement.adoc
Fix the "clean" into "test" for starting a test
=> Fix Documentation

ui/.eslintrc.json
background
- https://github.com/OpenEMS/openems/pull/2671
definition (these rules have compatibility of original eslint rules)
- https://eslint.style/rules/default/quotes
- https://eslint.style/rules/default/no-multiple-empty-lines
=> add @stylistic to style rules

ui/src/app/edge/live/Controller/ChpSoc/ChpSoc.html, ui/src/app/edge/live/Controller/ChpSoc/ChpSoc.ts
Update ChpSoc percentage bar styling
=> Fix ChpSoc style

doc/modules/ROOT/pages/ui/implementing-a-widget/components/chart.adoc
the Link has been corrected:
https://github.com/OpenEMS/openems/blob/9cbfdb2368fcadcb6ce5de5df84c8bb01079445d/ui/src/app/edge/history/common/autarchy/chart/chart.ts#
=> Update chart.adoc Link for GitHub Code

io.openems.edge.controller.api.mqtt/src/io/openems/edge/controller/api/mqtt/ControllerApiMqttImpl.java
synchronize reconnect logic to avoid duplicate attempts, update logWarn to use proper log level
=> MQTT: avoid duplicate connect attempts

doc/modules/ROOT/pages/backend/deploy.adoc
=> Update deploy.adoc: typo

io.openems.edge.core/src/io/openems/edge/core/host/HostImpl.java, io.openems.edge.core/src/io/openems/edge/core/host/OperatingSystemDocker.java, tools/docker/backend/Dockerfile, tools/docker/backend/root/etc/s6-overlay/s6-rc.d/svc-openems-backend/run, tools/docker/backend/root/var/lib/openems-default-config/Core/Cycle.config, tools/docker/backend/root/var/lib/openems-default-config/Core/Energy.config, tools/docker/backend/root/var/lib/openems-default-config/Core/Meta.config, tools/docker/backend/root/var/lib/openems-default-config/Core/Sum.config, tools/docker/edge/Dockerfile, tools/docker/edge/root/etc/s6-overlay/s6-rc.d/svc-openems-edge/run, tools/docker/edge/root/var/lib/openems-default-config/Core/AppManager.config, tools/docker/edge/root/var/lib/openems-default-config/Core/ComponentManager.config, tools/docker/edge/root/var/lib/openems-default-config/Core/Cycle.config, tools/docker/edge/root/var/lib/openems-default-config/Core/Energy.config, tools/docker/edge/root/var/lib/openems-default-config/Core/Meta.config, tools/docker/edge/root/var/lib/openems-default-config/Core/PredictorManager.config, tools/docker/edge/root/var/lib/openems-default-config/Core/SerialNumber.config, tools/docker/edge/root/var/lib/openems-default-config/Core/Sum.config, tools/docker/ui/Dockerfile, tools/docker/ui/root/defaults/nginx/openems-nginx.conf
* Improve Container creation; Reduce size by moving more work to the build container.
* Use Temurin JDK
* Add JVM settings
* Edge: Implement OperatingSystemDocker
* Add more core components to default setup
=> Improve Docker container

io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/HyperParameters.java, io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/LstmPredictor.java, io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/train/LstmTrain.java, io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/train/TrainAndValidateBatch.java, io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/util/Cell.java, io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/util/Lstm.java
- Implement dropout regularization in LSTM predictor for better model generalization
- Add scaling factors for dropout to maintain output magnitude during training
=> LSTM predictor with dropout regularization

io.openems.edge.weather.openmeteo/src/io/openems/edge/weather/openmeteo/HistoricalWeatherService.java, io.openems.edge.weather.openmeteo/src/io/openems/edge/weather/openmeteo/WeatherForecastService.java
This fixes a bug reported in https://community.openems.io/t/problems-using-openmeteo-forecast/10292/2
=> Open-Meteo: Fixed empty apikey parameter in url

tools/docker/backend/Dockerfile, tools/docker/backend/docker-compose.yml, tools/docker/backend/root/etc/s6-overlay/s6-rc.d/svc-openems-backend/run, tools/docker/edge/Dockerfile, tools/docker/edge/root/etc/s6-overlay/s6-rc.d/svc-openems-edge/run, tools/docker/ui/Dockerfile, tools/docker/ui/root/etc/s6-overlay/s6-rc.d/svc-openems-ui/run
* Set Apache Felix host and port explicitly
* Print error into docker console, if `UI_WEBSOCKET` is unchanged
* Format
=> Improve Docker

io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/sunspec/meter/AbstractSunSpecMeter.java, io.openems.edge.fronius/test/io/openems/edge/fronius/meter/MeterFroniusImplTest.java
Relates to https://community.openems.io/t/fronius-symo-liefert-keine-daten/2356/47
=> SunSpec Meter: invert energy channels mapping

.github/workflows/stale.yml
Extend messages, add formatting and provide relevant links
=> Extend auto Stale and Close messages
