ui/src/app/edge/history/energy/energy.component.ts, ui/src/app/edge/history/history.component.html, ui/src/app/edge/history/soc/soc.component.ts, ui/src/app/edge/live/channelthreshold/channelthreshold.component.html, ui/src/app/edge/live/consumption/consumption.component.html, ui/src/app/edge/live/consumption/modal/modal.component.html, ui/src/app/edge/live/evcs/evcs.component.ts, ui/src/app/edge/live/grid/grid.component.html, ui/src/app/edge/live/grid/modal/modal.component.html, ui/src/app/edge/live/production/modal/modal.component.html, ui/src/app/edge/live/production/production.component.html, ui/src/app/edge/live/production/production.component.ts, ui/src/app/edge/live/storage/modal/modal.component.html, ui/src/app/edge/live/storage/storage.component.html, ui/src/app/shared/edge/currentdata.ts, ui/src/app/shared/edge/edgeconfig.ts, ui/src/app/shared/pipe/unitvalue/unitvalue.pipe.ts, ui/src/app/shared/shared.module.ts, ui/src/app/shared/translate/de.ts, ui/src/app/shared/type/widget.ts
fixed that all channelthreshold controller are shown in live component (*not just the active ones)
fixed that the colors remain the same in energy chart if edge has no storage
fixed that 'null' values are shown
- added unitValue pipe
=> Fixes of Channelthreshold/Colors in History Chart/'Null' values

cnf/pom.xml, io.openems.common/src/io/openems/common/OpenemsConstants.java, io.openems.edge.application/EdgeApp.bndrun, io.openems.edge.common/src/io/openems/edge/common/channel/Channel.java, io.openems.edge.common/src/io/openems/edge/common/channel/internal/AbstractReadChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/value/Value.java, io.openems.edge.common/src/io/openems/edge/common/type/CircularTreeMap.java, io.openems.edge.common/test/io/openems/edge/common/type/CircularTreeMapTest.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/RestApi.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/RestHandler.java, io.openems.edge.timedata.rrd4j/.classpath, io.openems.edge.timedata.rrd4j/.gitignore, io.openems.edge.timedata.rrd4j/.project, io.openems.edge.timedata.rrd4j/bnd.bnd, io.openems.edge.timedata.rrd4j/readme.adoc, io.openems.edge.timedata.rrd4j/src/io/openems/edge/timedata/rrd4j/Config.java, io.openems.edge.timedata.rrd4j/src/io/openems/edge/timedata/rrd4j/RecordWorker.java, io.openems.edge.timedata.rrd4j/src/io/openems/edge/timedata/rrd4j/Rrd4jTimedata.java
- Introduce new environment variable "openems.data.dir". Rrd4j data is stored in this directory
- "Channel" now keeps the past 100 values in a local cache; TODO: use this everywhere where we are currently doing this manually, e.g. BackendApi
- Channel "Value" now keeps a timestamp of when the value was set
- Add JSON-RPC requests for QueryHistoricTimeseriesData and QueryHistoricTimeseriesEnergy to JSON/REST Api
- Add CircularTreeMap type - it is used for the past values mentioned above
=> Implement timedata service based on Rrd4j

io.openems.common/src/io/openems/common/types/EdgeConfig.java, io.openems.edge.common/src/io/openems/edge/common/channel/ChannelId.java, io.openems.edge.common/src/io/openems/edge/common/component/AbstractOpenemsComponent.java, io.openems.edge.common/src/io/openems/edge/common/component/OpenemsComponent.java, io.openems.edge.common/src/io/openems/edge/common/type/TypeUtils.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/ComponentManagerImpl.java, io.openems.edge.fenecon.dess/src/io/openems/edge/fenecon/dess/gridmeter/FeneconDessGridMeter.java, io.openems.edge.fenecon.dess/src/io/openems/edge/fenecon/dess/pvmeter/FeneconDessPvMeter.java, io.openems.edge.fenecon.mini/src/io/openems/edge/fenecon/mini/gridmeter/FeneconMiniGridMeter.java, io.openems.edge.fenecon.mini/src/io/openems/edge/fenecon/mini/pvmeter/FeneconMiniPvMeter.java, io.openems.edge.fenecon.pro/src/io/openems/edge/fenecon/pro/pvmeter/FeneconProPvMeter.java, io.openems.edge.goodwe.et/src/io/openems/edge/goodwe/et/gridmeter/GoodWeEtGridMeter.java, io.openems.edge.kostal.piko/src/io/openems/edge/kostal/piko/gridmeter/KostalPikoGridMeter.java, io.openems.edge.pvinverter.cluster/src/io/openems/edge/pvinverter/cluster/PvInverterCluster.java, io.openems.edge.pvinverter.kaco.blueplanet/src/io/openems/edge/pvinverter/kaco/blueplanet/KacoBlueplanet.java, io.openems.edge.pvinverter.solarlog/src/io/openems/edge/pvinverter/solarlog/SolarLog.java, io.openems.edge.pvinverter.sunspec/src/io/openems/edge/pvinverter/sunspec/SunSpecPvInverter.java, io.openems.edge.simulator/src/io/openems/edge/simulator/meter/grid/acting/GridMeter.java, io.openems.edge.simulator/src/io/openems/edge/simulator/meter/grid/reacting/GridMeter.java, io.openems.edge.simulator/src/io/openems/edge/simulator/meter/production/acting/ProductionMeter.java, io.openems.edge.simulator/src/io/openems/edge/simulator/pvinverter/PvInverter.java, io.openems.edge.solaredge/src/io/openems/edge/solaredge/gridmeter/SolarEdgeGridMeter.java, io.openems.edge.solaredge/src/io/openems/edge/solaredge/pvinverter/SolarEdge.java, ui/src/app/shared/edge/edgeconfig.ts
- For every Configuration Property (= "Config" annotation) a Channel "_PropertyConfigname" is automatically generated with the configured value
- Channels starting with underscore ("_") are documented as "reserved for internal usage"
- Improve how the value for a String-Channel is set; better handling for Arrays
- EdgeConfig now has every Property; even the ones defined via "@Component" annotation. This allows setting "type=PRODUCTION" for Meters.
- Add "type" property to all existing specific Grid-/Production-Meters
=> Improve EdgeConfig & create Channel for each configuration Property

cnf/checkstyle.xml, io.openems.backend.application/BackendApp.bndrun, io.openems.backend.b2brest/src/io/openems/backend/b2brest/B2bRest.java, io.openems.backend.b2brest/src/io/openems/backend/b2brest/RestHandler.java, io.openems.backend.b2bwebsocket/bnd.bnd, io.openems.backend.b2bwebsocket/src/io/openems/backend/b2bwebsocket/B2bWebsocket.java, io.openems.backend.b2bwebsocket/src/io/openems/backend/b2bwebsocket/OnRequest.java, io.openems.backend.common/bnd.bnd, io.openems.backend.common/src/io/openems/backend/common/jsonrpc/JsonRpcRequestHandler.java, io.openems.backend.core/.classpath, io.openems.backend.core/.gitignore, io.openems.backend.core/.project, io.openems.backend.core/bnd.bnd, io.openems.backend.core/readme.md, io.openems.backend.core/src/io/openems/backend/core/jsonrpcrequesthandler/EdgeRpcRequestHandler.java, io.openems.backend.core/src/io/openems/backend/core/jsonrpcrequesthandler/JsonRpcRequestHandlerImpl.java, io.openems.backend.metadata.api/bnd.bnd, io.openems.backend.uiwebsocket.impl/src/io/openems/backend/uiwebsocket/impl/OnRequest.java, io.openems.backend.uiwebsocket.impl/src/io/openems/backend/uiwebsocket/impl/UiWebsocketImpl.java
This assures that all JSON-RPC requests are available from every API interface and avoids duplicated code.
=> Backend: move handling of JSON-RPC requests to separate handler component

io.openems.edge.timedata.influxdb/src/io/openems/edge/timedata/influxdb/Config.java, io.openems.edge.timedata.influxdb/src/io/openems/edge/timedata/influxdb/InfluxTimedata.java
I added an Option to set a no of cycles to the influxdb module.
With that I can avoid a lot of unnecessary write accesses on the device that hosts the Edge Component.
In my case I don't need to write data every second, but my main cycletime of the scheduler is 1s.
As the smallest intervall in history points in the UI are 5 minutes, I can for example set a no of cycles of 300.
=> added no of cycles option to influxdb module.

io.openems.common/src/io/openems/common/jsonrpc/request/CreateComponentConfigRequest.java, io.openems.common/src/io/openems/common/jsonrpc/request/UpdateComponentConfigRequest.java, io.openems.edge.common/src/io/openems/edge/common/component/ComponentManager.java, io.openems.edge.core/readme.adoc, io.openems.edge.core/src/io/openems/edge/core/componentmanager/ComponentManagerImpl.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/DefaultConfigurationWorker.java
Add DefaultConfigurationWorker. Creates default configurations for deployment.
By default it makes sure that JSON/REST Api and Modbus/TCP-Slave Api are always configured by default in their read-only variants
=> Add DefaultConfigurationWorker. Creates default configurations for deployment.

io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/EdgeCache.java, io.openems.common/src/io/openems/common/types/EdgeConfig.java, io.openems.common/src/io/openems/common/types/EdgeConfigDiff.java, io.openems.edge.common/src/io/openems/edge/common/component/ComponentManager.java, io.openems.edge.common/src/io/openems/edge/common/test/DummyComponentManager.java, io.openems.edge.controller.api.backend/src/io/openems/edge/controller/api/backend/BackendApi.java, io.openems.edge.controller.api.backend/src/io/openems/edge/controller/api/backend/OnOpen.java, io.openems.edge.controller.api.websocket/src/io/openems/edge/controller/api/websocket/WebsocketApi.java, io.openems.edge.controller.ess.limitdischargecellvoltage/test/io/openems/edge/controller/ess/limitdischargecellvoltage/helper/DummyComponentManager.java, io.openems.edge.core/bnd.bnd, io.openems.edge.core/src/io/openems/edge/core/componentmanager/ComponentManagerImpl.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/EdgeConfigFactory.java, ui/src/app/shared/edge/edgeconfig.ts
- remove "isEnabled"; it's already covered by the 'enabled' property
- improve "getAsText" method
- Websocket.Api: do not collect EdgeConfig if no websocket is connected
- Create EdgeConfigFactory that takes care of building and caching EdgeConfig
- Cache EdgeConfig and only incorporate ConfigurationEvents on Change; improves speed a lot
=> Improvements in EdgeConfig handling

cnf/pom.xml, io.openems.backend.application/BackendApp.bndrun, io.openems.edge.application/EdgeApp.bndrun, tools/prepare-commit.sh
Fixes an issue that caused an exception at startup which caused all components listed in 'runbundles' after org.ops4j.pax.logging.pax-logging-service to stop working.
The problem came up in OpenEMS Community Forum: https://community.openems.io/t/cannot-activate-template-controller/198/10. Thanks to Valentin and @clehne for helping to track it down and fix it.
=> Update PAX Logging to 2.0.2

ui/src/app/shared/edge/edgeconfig.ts
This avoids errors if some edge deployments don't have every nature available.
=> added check if nature ist defined in getFactoriesByNature()

io.openems.edge.goodwe.et/src/io/openems/edge/goodwe/et/ess/GoodWeEtBatteryInverterImpl.java
Removed setting “Off-grid” mode in EMS-power-mode which was causing the system to enter off-grid mode during the initial few minutes. The system is taking quite a few seconds to set the grid mode to on-grid, initially, it is undefined so the power mode enters into the off-grid mode and taking a while to change it back to on-grid.
Changed the charging command condition to work when active power is 0.
Fixed Null pointer exception which was caused during the starting of the system for the first time.
=> Removed setting "Off grid" mode in EMS power mode and Null Pointer Exception

io.openems.edge.common/src/io/openems/edge/common/type/TypeUtils.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/DiscovergyApiClient.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/DiscovergyWorker.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/MeterDiscovergy.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/jsonrpc/Field.java, io.openems.edge.meter.discovergy/src/io/openems/edge/meter/discovergy/jsonrpc/GetFieldNamesResponse.java
Discovergy started to invert their power values for Production. See https://forum.discovergy.com/t/wieso-werden-meine-ertragsdaten-der-solaranlage-negativ-dargestellt/998/22
This Pull-Request fixes this by inverting the value when needed. It also adds the raw data as channels for easier debugging
=> Fix Discovergy implementation with latest API for Production meters

io.openems.edge.io.wago/src/io/openems/edge/wago/Fieldbus4xxDI.java, io.openems.edge.io.wago/src/io/openems/edge/wago/Fieldbus5xxDO.java, io.openems.edge.io.wago/src/io/openems/edge/wago/FieldbusModuleFactory.java, io.openems.edge.io.wago/src/io/openems/edge/wago/Wago.java
- Tries to read old 'ea-config.xml' and new 'io_config.xml'
- Dynamically reads the number of output channels from xml file for WAGO 750 5xx-modules
=> WAGO: compatibility with newer fieldbus couplers + all kinds of digital output modules

ui/src/app/edge/history/heatingelement/chart.component.ts, ui/src/app/edge/live/chpsoc/chpsoc.component.ts, ui/src/app/edge/live/chpsoc/modal/modal.component.html, ui/src/app/edge/live/chpsoc/modal/modal.component.ts, ui/src/app/edge/live/consumption/consumption.component.html, ui/src/app/edge/live/consumption/consumption.component.ts, ui/src/app/edge/live/consumption/modal/modal.component.html, ui/src/app/edge/live/consumption/modal/modal.component.ts, ui/src/app/edge/live/evcs/modal/modal.page.html, ui/src/app/edge/live/fixdigitaloutput/modal/modal.component.html, ui/src/app/edge/live/heatingelement/modal/modal.component.html, ui/src/app/edge/live/heatingelement/modal/modal.component.ts, ui/src/app/edge/live/live.module.ts, ui/src/app/edge/live/singlethreshold/modal/modal.component.html
UI: 
-add possibility to pick level when heatingelement is set to MANUAL_ON in heatingelement advanced widget
-add help button which link to fenecon docs for chpsoc, evcs, singlethreshold, heatingelement and fixdigitaloutput - advanced widget
-add metered consumption to consumption flat and advanced widget 
-remove workmode kwh from heatingelement advanced widget
=> small ui adjustments

io.openems.common/src/io/openems/common/utils/JsonUtils.java, io.openems.common/src/io/openems/common/websocket/OnOpen.java, io.openems.common/test/io/openems/common/websocket/OnOpenTest.java
HTTP header field names shouldn't be case sensitive as per [specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).
This is not the most elegant solution, but it will fix errors with APIs that force using lowercase characters. If someone can think of more elegant approaches, feel free to comment.
=> Fix cookie HTTP header field name being case sensitive

ui/src/app/app.component.ts, ui/src/app/edge/live/chpsoc/chpsoc.component.html, ui/src/app/edge/live/chpsoc/modal/modal.component.html, ui/src/app/edge/live/chpsoc/modal/modal.component.ts, ui/src/app/edge/live/evcsCluster/modal/evcs-chart/evcs.chart.ts
- change adjustable thresholds from 15-85 to 0-100
- adjust flat widget svg to be able to show new thresholds
- remove console.logs
Before with 5-95 (configured manually via fems settings):
After with 5-95:
Before with regular settings: (between 15-85):
After with regular settings:
=> update CHPSoC widget % thresholds

io.openems.edge.timedata.rrd4j/src/io/openems/edge/timedata/rrd4j/RecordWorker.java, io.openems.edge.timedata.rrd4j/src/io/openems/edge/timedata/rrd4j/Rrd4jTimedataImpl.java
Implemented queryHistoricEnergy()
- Fixed bug in ChannelDef for energy channels.
- fixed bug where lastTimestamp was never reassigned
Tested with version 2020.16.0 on iot2020 as host
=> RRD4J: Implement historic energy

io.openems.common/src/io/openems/common/jsonrpc/request/SetGridConnScheduleRequest.java, io.openems.edge.common/src/io/openems/edge/common/component/OpenemsComponent.java, io.openems.edge.common/src/io/openems/edge/common/test/AbstractComponentConfig.java, io.openems.edge.common/src/io/openems/edge/common/test/AbstractComponentTest.java, io.openems.edge.common/src/io/openems/edge/common/test/DummyComponentContext.java, io.openems.edge.common/src/io/openems/edge/common/test/DummyConfigurationAdmin.java, io.openems.edge.controller.symmetric.balancingschedule/readme.adoc, io.openems.edge.controller.symmetric.balancingschedule/src/io/openems/edge/controller/symmetric/balancingschedule/BalancingSchedule.java, io.openems.edge.controller.symmetric.balancingschedule/src/io/openems/edge/controller/symmetric/balancingschedule/BalancingScheduleImpl.java, io.openems.edge.controller.symmetric.balancingschedule/src/io/openems/edge/controller/symmetric/balancingschedule/Config.java, io.openems.edge.controller.symmetric.balancingschedule/test/io/openems/edge/controller/symmetric/balancingschedule/BalancingScheduleImplTest.java, io.openems.edge.controller.symmetric.balancingschedule/test/io/openems/edge/controller/symmetric/balancingschedule/MyConfig.java
This refactoring of the existing "Balancing Schedule Controller" comes with:
- proper documentation (readme.adoc)
- introduction of `GridActivePowerSetPoint` for direct setting of a power target set-point at the grid connection point
- thorough JUnit tests
- applied latest OpenEMS code quality and best practices
- improvements to the OpenEMS JUnit test framework
=> Refactor Balancing Schedule Controller

.travis.yml, io.openems.backend.application/BackendApp.bndrun, tools/prepare-commit.sh
- Let Travis fail if resolving changes the existing bndrun files
- Always update EdgeApp + BackendApp bndrun files in prepare-commit script 
- Fix existing resolve error in BackendApp.bndrun
=> Avoid resolve errors in EdgeApp and BackendApp.bndrun

io.openems.common/src/io/openems/common/types/EdgeConfig.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/DefaultConfigurationWorker.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/OsgiValidateWorker.java
- DefaultConfigurationWorker: add logging on action
- OsgiValidateWorker: search for duplicated Component-IDs in all configurations, not only enabled ones
- EdgeConfig: allow setting ".target" properties
=> Improvements to ComponentManager workers

io.openems.edge.core/src/io/openems/edge/core/cycle/CycleWorker.java, io.openems.edge.scheduler.allalphabetically/src/io/openems/edge/scheduler/allalphabetically/AllAlphabeticallySchedulerImpl.java, io.openems.edge.scheduler.allalphabetically/test/io/openems/edge/scheduler/allalphabetically/AllAlphabeticallyTest.java, io.openems.edge.scheduler.api/src/io/openems/edge/scheduler/api/Scheduler.java, io.openems.edge.scheduler.daily/src/io/openems/edge/scheduler/daily/DailySchedulerImpl.java, io.openems.edge.scheduler.daily/test/io/openems/edge/scheduler/daily/DailySchedulerImplTest.java, io.openems.edge.scheduler.fixedorder/src/io/openems/edge/scheduler/fixedorder/FixedOrderSchedulerImpl.java, io.openems.edge.scheduler.fixedorder/test/io/openems/edge/scheduler/fixedorder/FixedOrderSchedulerImplTest.java
- Missing Controller does not anymore cause a fatal Scheduler error
- Scheduler now only returns a sorted set of Controller-IDs
- New Scheduler-Channel "ControllerIsMissing"
=> Scheduler: improve handling of errors

io.openems.edge.batteryinverter.kaco.blueplanetgridsave/src/io/openems/edge/batteryinverter/kaco/blueplanetgridsave/KacoBlueplanetGridsaveImpl.java, io.openems.edge.batteryinverter.kaco.blueplanetgridsave/src/io/openems/edge/batteryinverter/kaco/blueplanetgridsave/KacoSunSpecModel.java, io.openems.edge.batteryinverter.kaco.blueplanetgridsave/src/io/openems/edge/batteryinverter/kaco/blueplanetgridsave/statemachine/RunningHandler.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/element/AbstractWordElement.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/element/SignedWordElement.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/element/UnsignedWordElement.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/sunspec/SunSpecPoint.java, io.openems.edge.ess.api/src/io/openems/edge/ess/api/SymmetricEss.java, io.openems.edge.pvinverter.sunspec/src/io/openems/edge/pvinverter/sunspec/SetPvLimitHandler.java
The SunSpec protocol definition uses integer registers with separate scalefactor-definitions in separate registers. Due to the way OpenEMS is setting a register from a Write-Channel, the value was rounded to integer before the scalefactor was applied.
This pull request fixes the behaviour by using FloatWriteChannels instead of IntegerWriteChannels for SunSpec registers with scalefactor.
=> Fix SunSpec: rounding issues with ScaleFactors

io.openems.edge.battery.bmw/src/io/openems/edge/battery/bmw/BmwBatteryImpl.java
- Register 1006 MAXIMUM_OPERATING_CURRENT (sign)
- Register 1010 DISCHARGE_MAX_CURRENT (sign)
- Register 1029 CURRENT (sign and scale factor)
- Register 1030 AVERAGE_TEMPERATURE (sign)
- Register 1031 MIN_CELL_TEMPERATURE (sign)
- Register 1032 MAX_CELL_TEMPERATURE (sign)
- Register 1037 INSULATION_RESISTANCE (scale factor)
- Register 1041 MAXIMUM_LIMIT_DYNAMIC_CURRENT_HIGH_RES (sign)
- Register 1042 MINIMUM_LIMIT_DYNAMIC_CURRENT_HIGH_RES (sign)
=> wrong datatypes and scale factors @ BMW modbus implementation changed

cnf/pom.xml, io.openems.backend.application/BackendApp.bndrun, io.openems.edge.application/EdgeApp.bndrun
It seems like https://github.com/apache/felix-dev/commit/4102a86b92d26e64a91fcb0e8e4eaa24f561dad9 was breaking empty target filters
=> Downgrade apache.felix.scr to 2.1.20

io.openems.backend.b2bwebsocket/src/io/openems/backend/b2bwebsocket/B2bWebsocket.java, io.openems.backend.b2bwebsocket/src/io/openems/backend/b2bwebsocket/SubscribedEdgesChannelsWorker.java, io.openems.backend.b2bwebsocket/src/io/openems/backend/b2bwebsocket/WsData.java, io.openems.backend.b2bwebsocket/test/io/openems/backend/b2bwebsocket/TestClient.java, io.openems.backend.edgewebsocket/src/io/openems/backend/edgewebsocket/EdgeWebsocketImpl.java, io.openems.backend.edgewebsocket/src/io/openems/backend/edgewebsocket/WebsocketServer.java, io.openems.backend.edgewebsocket/src/io/openems/backend/edgewebsocket/WsData.java, io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/postgres/PeriodicWriteWorker.java, io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/postgres/QueueWriteWorker.java, io.openems.backend.uiwebsocket/src/io/openems/backend/uiwebsocket/impl/WebsocketServer.java, io.openems.backend.uiwebsocket/src/io/openems/backend/uiwebsocket/impl/WsData.java, io.openems.common/src/io/openems/common/utils/ThreadPoolUtils.java, io.openems.common/src/io/openems/common/websocket/AbstractWebsocket.java, io.openems.common/src/io/openems/common/websocket/AbstractWebsocketClient.java, io.openems.common/src/io/openems/common/websocket/AbstractWebsocketServer.java, io.openems.common/src/io/openems/common/websocket/DummyWebsocketServer.java, io.openems.common/src/io/openems/common/websocket/DummyWsData.java, io.openems.common/src/io/openems/common/websocket/SubscribedChannelsWorker.java, io.openems.common/src/io/openems/common/websocket/WsData.java, io.openems.edge.controller.api.backend/src/io/openems/edge/controller/api/backend/BackendApiImpl.java, io.openems.edge.controller.api.backend/src/io/openems/edge/controller/api/backend/SendChannelValuesWorker.java, io.openems.edge.controller.api.backend/src/io/openems/edge/controller/api/backend/WebsocketClient.java, io.openems.edge.controller.api.backend/src/io/openems/edge/controller/api/backend/WsData.java, io.openems.edge.controller.api.websocket/src/io/openems/edge/controller/api/websocket/WebsocketApi.java, io.openems.edge.controller.api.websocket/src/io/openems/edge/controller/api/websocket/WsData.java, io.openems.shared.influxdb/src/io/openems/shared/influxdb/InfluxConnector.java
- Reduce the total number of ThreadPools (before there was one ThreadPool per WebSocket. Now it's one per Component.)
- Set namespace for ThreadPools to simplify debugging
=> OpenEMS Backend: optimize ThreadPools

io.openems.common/src/io/openems/common/types/EdgeConfig.java, io.openems.common/src/io/openems/common/utils/JsonUtils.java, io.openems.edge.common/src/io/openems/edge/common/channel/internal/AbstractDoc.java, io.openems.edge.common/src/io/openems/edge/common/component/AbstractOpenemsComponent.java, io.openems.edge.controller.api.backend/test/io/openems/edge/controller/api/backend/BackendApiImplTest.java
For each configuration property of an OpenEMS Component automatically a `_Property` Channel is created, e.g. `_PropertyEnabled` for the `enabled` configuration.
Currently the type of the Channel is guessed at runtime. This pull-request takes the information directly from `MetaTypeInformation` provided by the `MetaTypeService`. Additionally properties marked as password, will be not anymore published to Channels to avoid security issues.
=> Use MetaTypeInformation for `_Property` Channels

io.openems.edge.common/src/io/openems/edge/common/component/AbstractOpenemsComponent.java, io.openems.edge.common/src/io/openems/edge/common/type/TypeUtils.java
- Tries to extract 'one' value of the array
- Falls back to 'STRING' if there are more two or more values
- Handle 'IllegalArgumentException' instead of fail
=> Array-Properties: handle datatype properly

io.openems.edge.battery.api/src/io/openems/edge/battery/protection/BatteryProtection.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/AbstractOpenemsModbusComponent.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/ChannelMetaInfo.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/ChannelMetaInfoBit.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/ChannelMetaInfoReadAndWrite.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/ChannelToElementConverter.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/element/BitsWordElement.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/element/ModbusReadElement.java, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/element/ModbusWriteElement.java, io.openems.edge.common/src/io/openems/edge/common/channel/BooleanWriteChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/Channel.java, io.openems.edge.common/src/io/openems/edge/common/channel/DoubleWriteChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/EnumWriteChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/FloatWriteChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/IntegerWriteChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/LongWriteChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/ShortWriteChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/StringWriteChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/WriteChannel.java, io.openems.edge.common/src/io/openems/edge/common/channel/internal/AbstractReadChannel.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/jsonrpc/ChannelExportXlsxResponse.java, io.openems.edge.fenecon.mini/src/io/openems/edge/fenecon/mini/ess/FeneconMiniEssImpl.java, io.openems.edge.fenecon.pro/src/io/openems/edge/fenecon/pro/ess/FeneconProEss.java, io.openems.edge.pvinverter.solarlog/src/io/openems/edge/pvinverter/solarlog/SolarLogImpl.java, io.openems.wrapper.eu.chargetime.ocpp/generated/buildfiles
The Channel Source and Target information introduced in #1595 was not working, because Read-Write-Channel information would always be considered a 'target' information. This Pull-Request refactors the information to a generic MetaInfo and allows explicit definition of different read- and write-registers for one Channel
=> Fix and refactor Channel Meta-Info

io.openems.common/src/io/openems/common/OpenemsConstants.java, io.openems.common/src/io/openems/common/types/EdgeConfig.java, io.openems.common/src/io/openems/common/websocket/AbstractWebsocketServer.java, io.openems.edge.common/src/io/openems/edge/common/component/ComponentManager.java, io.openems.edge.common/src/io/openems/edge/common/component/OpenemsComponent.java, io.openems.edge.common/src/io/openems/edge/common/cycle/Cycle.java, io.openems.edge.common/src/io/openems/edge/common/host/Host.java, io.openems.edge.common/src/io/openems/edge/common/meta/Meta.java, io.openems.edge.common/src/io/openems/edge/common/sum/DummySum.java, io.openems.edge.common/src/io/openems/edge/common/sum/Sum.java, io.openems.edge.common/src/io/openems/edge/common/test/DummyComponentManager.java, io.openems.edge.controller.api.backend/src/io/openems/edge/controller/api/backend/OnRequest.java, io.openems.edge.controller.api.backend/test/io/openems/edge/controller/api/backend/BackendApiImplTest.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/RestHandler.java, io.openems.edge.controller.api.websocket/src/io/openems/edge/controller/api/websocket/OnRequest.java, io.openems.edge.controller.generic.jsonlogic/test/io/openems/edge/controller/generic/jsonlogic/JsonLogicControllerTest.java, io.openems.edge.controller.generic.jsonlogic/test/io/openems/edge/controller/generic/jsonlogic/JsonLogicControllerTest2.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/ComponentManagerImpl.java, io.openems.edge.core/src/io/openems/edge/core/componentmanager/EdgeConfigWorker.java, io.openems.edge.core/src/io/openems/edge/core/cycle/CycleImpl.java, io.openems.edge.core/src/io/openems/edge/core/host/HostImpl.java, io.openems.edge.core/src/io/openems/edge/core/meta/MetaImpl.java, io.openems.edge.core/src/io/openems/edge/core/predictormanager/PredictorManagerImpl.java, io.openems.edge.core/src/io/openems/edge/core/sum/SumImpl.java, io.openems.edge.predictor.api/src/io/openems/edge/predictor/api/manager/PredictorManager.java, io.openems.edge.predictor.api/src/io/openems/edge/predictor/api/test/DummyPredictorManager.java, io.openems.edge.predictor.persistencemodel/src/io/openems/edge/predictor/deprecatedpersistencemodel/consumption/ConsumptionPredictor.java, io.openems.edge.predictor.persistencemodel/src/io/openems/edge/predictor/deprecatedpersistencemodel/prediction/ProductionPredictor.java, io.openems.edge.simulator/src/io/openems/edge/simulator/app/SimulatorApp.java, io.openems.edge.timedata.api/src/io/openems/edge/timedata/api/utils/CalculateActiveTime.java
Latest version of Apache WebConsole does not explicitely store unchanged default configuration properties. This has certain implications on the way OpenEMS uses properties, e.g. it means that a Component that is created via Apache WebConsole with default 'id' does not have the 'id' stored as property.
See this issue for details:
https://issues.apache.org/jira/browse/FELIX-6436?focusedCommentId=17412472&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17412472
=> Fix compatibility with Apache WebConsole 4.7.0

io.openems.edge.application/EdgeApp.bndrun, io.openems.edge.timeofusetariff.corrently/readme.adoc, io.openems.edge.timeofusetariff.tibber/.classpath, io.openems.edge.timeofusetariff.tibber/.gitignore, io.openems.edge.timeofusetariff.tibber/.project, io.openems.edge.timeofusetariff.tibber/bnd.bnd, io.openems.edge.timeofusetariff.tibber/readme.adoc, io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/Config.java, io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/Tibber.java, io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/TibberImpl.java, io.openems.edge.timeofusetariff.tibber/test/io/openems/edge/timeofusetariff/tibber/MyConfig.java, io.openems.edge.timeofusetariff.tibber/test/io/openems/edge/timeofusetariff/tibber/TibberProviderTest.java
Implemented Tibber API to retrieve the prices for Time-Of-Use Tariff API service.
Coorent readme doc for corrently.
Co-authored-by: Stefan Feilmeier <stefan.feilmeier@fenecon.de>
Reviewed-by: Stefan Feilmeier <stefan.feilmeier@fenecon.de>
Co-authored-by: Sagar Venu <sagar.venu@fenecon.de>
=> Add Time-Of-Use Tariff Tibber

io.openems.edge.ess.cluster/src/io/openems/edge/ess/cluster/ChannelManager.java, io.openems.edge.ess.cluster/test/io/openems/edge/ess/cluster/EssClusterTest.java
Certain Channels like 'Capacity' or 'ActivePowerL1/L2/L3' had not been calculated at all or correctly.
=> Ess-Cluster: fix calculation of channel

cnf/pom.xml, io.openems.backend.application/BackendApp.bndrun, io.openems.backend.application/src/io/openems/backend/application/BackendApp.java, io.openems.edge.application/EdgeApp.bndrun, io.openems.edge.core/src/io/openems/edge/core/componentmanager/DefaultConfigurationWorker.java
Hi Stefan,
as discussed in the [community](https://community.openems.io/t/schwachstelle-in-log4j-und-openems/707/5), I have created a merge request regarding my Log4J2 changes.
The idea is to use a `PaxOsgi`appender, as described [here](https://ops4j1.jira.com/wiki/spaces/paxlogging/pages/499613746/Configuring+Log4J2).
I was able to test the changes successfully for the OpenEMS edge running on my local machine. However, the configuration file in 'pax/logging.config' is not updated when I start the backend locally.
Unfortunately, I was not able to find out why, but the problem already existed before applying my changes, so it might be an issue with the development branch.
Originally, I have developed these changes for a slightly older version of OpenEMS which still runs on Java 8. On this …
=> Switch to log4j2

cnf/pom.xml, io.openems.edge.application/EdgeApp.bndrun, io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/BridgeModbusSerialImpl.java
We have been trying a couple of times already to update j2mod and jSerialComm to there latest version, but it always fails, because jSerialComm somehow reconfigures the serial device and draws it unusable on our test systems. If anybody can help out, it will be much appreciated. Till then we will stay with the old version.
=> Downgrade j2mod/jSerialComm

io.openems.edge.core/src/io/openems/edge/core/componentmanager/EdgeConfigWorker.java
For some more complex OpenEMS Components primitive configuration settings are not sufficient. In such cases we use a String that holds a JSON object or array. 
This improvement tries to detect such complex JSON elements and parses them within EdgeConfig
=> EdgeConfig: try to parse JSON configurations

cnf/pom.xml, io.openems.edge.application/EdgeApp.bndrun, io.openems.wrapper/bnd.bnd, io.openems.wrapper/eu.chargetime.ocpp.bnd, io.openems.wrapper/javax.activation.bnd, io.openems.wrapper/sdnotify.bnd
With Java 11 `javax.activation` was dropped from the JRE. This adds the library as an explicit dependency.
=> Fix OCPP dependencies for Java 11

doc/modules/ROOT/pages/edge/deploy.adoc
Simplify systemd service file in deploy docs to avoid repeatingly appearing problems:
https://community.openems.io/t/probleme-beim-starten-der-edge-auf-einem-beaglebone/700/4
https://community.openems.io/t/error-while-deploying-openems-edge-on-wsl2-ubuntu/780
=> Improve docs for Deploy OpenEMS Edge

io.openems.common/src/io/openems/common/OpenemsConstants.java, io.openems.common/src/io/openems/common/types/OptionsEnum.java, io.openems.edge.common/src/io/openems/edge/common/channel/EnumDoc.java, io.openems.edge.common/src/io/openems/edge/common/component/OpenemsComponent.java, io.openems.edge.common/src/io/openems/edge/common/modbusslave/ModbusRecordChannel.java, io.openems.edge.common/src/io/openems/edge/common/modbusslave/ModbusRecordFloat32.java, io.openems.edge.common/src/io/openems/edge/common/modbusslave/ModbusRecordFloat64.java, io.openems.edge.common/src/io/openems/edge/common/modbusslave/ModbusRecordString16.java, io.openems.edge.common/src/io/openems/edge/common/modbusslave/ModbusRecordUint16.java, io.openems.edge.common/src/io/openems/edge/common/modbusslave/ModbusRecordUint16Hash.java, io.openems.edge.common/src/io/openems/edge/common/modbusslave/ModbusRecordUint32.java, io.openems.edge.common/src/io/openems/edge/common/modbusslave/ModbusSlaveNatureTable.java, io.openems.edge.common/src/io/openems/edge/common/modbusslave/ModbusType.java, io.openems.edge.common/src/io/openems/edge/common/sum/Sum.java, io.openems.edge.controller.api.modbus/src/io/openems/edge/controller/api/modbus/jsonrpc/GetModbusProtocolExportXlsxResponse.java, io.openems.edge.ess.api/src/io/openems/edge/ess/api/AsymmetricEss.java, io.openems.edge.ess.api/src/io/openems/edge/ess/api/CalculateGridMode.java, io.openems.edge.ess.api/src/io/openems/edge/ess/api/HybridEss.java, io.openems.edge.ess.api/src/io/openems/edge/ess/api/SymmetricEss.java, io.openems.edge.meter.api/src/io/openems/edge/meter/api/SymmetricMeter.java, io.openems.edge.simulator/src/io/openems/edge/simulator/evcs/AsymmetricMeterEvcs.java
GridMode can now be read via Modbus Address `417`.
Additionally:
- Add new type `enum16`
- Show `text` of Channels in Description
- Improve texts for Channels
- Fix calculation of GridMode when there is no ESS.
Co-authored-by: Michael Grill <michael.grill@fenecon.de>
Co-authored-by: Stefan Feilmeier <stefan.feilmeier@fenecon.de>
Reviewed-by: Stefan Feilmeier <stefan.feilmeier@fenecon.de>
Reviewed-by: Jan Seidemann <jan.seidemann@fenecon.de>
=> Modbus/TCP: Add GridMode to Sum (#204)

io.openems.edge.controller.io.heatingelement/bnd.bnd, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/Config.java, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/ControllerHeatingElement.java, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/ControllerHeatingElementImpl.java, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/Mode.java, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/Phase.java, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/PhaseDef.java, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/enums/Level.java, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/enums/Mode.java, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/enums/Phase.java, io.openems.edge.controller.io.heatingelement/src/io/openems/edge/controller/io/heatingelement/enums/WorkMode.java, io.openems.edge.controller.io.heatingelement/test/io/openems/edge/controller/io/heatingelement/HeatingElementTest.java, io.openems.edge.controller.io.heatingelement/test/io/openems/edge/controller/io/heatingelement/HeatingElementTest2.java, io.openems.edge.controller.io.heatingelement/test/io/openems/edge/controller/io/heatingelement/HeatingElementTestManual.java, io.openems.edge.controller.io.heatingelement/test/io/openems/edge/controller/io/heatingelement/MyConfig.java, ui/src/app/edge/history/heatingelement/widget.component.ts
Add cummulated time channels & update them depending on the current level.
Use this channels in the UI history.
Co-authored-by: Sebastian Asen <sebastian.asen@fenecon.de>
Co-authored-by: Lukas Rieger <lukas.rieger@fenecon.de>
Co-authored-by: Maximilian Lang <maximilian.lang@fenecon.de>
Co-authored-by: Stefan Feilmeier <stefan.feilmeier@fenecon.de>
=> Controller IO HeatingElement: add cumulated active time

ui/src/app/shared/edge/edgeconfig.ts
Fixes a bug that had been introduced by #1749
Under certain circumstances this bug would cause Production meters to be not displayed.
Thanks danielco for pointing it out in the OpenEMS Community forum: https://community.openems.io/t/trying-to-simulate-pv-production/838
=> UI bugfix `isProducer()` method

io.openems.shared.influxdb/src/io/openems/shared/influxdb/InfluxConnector.java
Tested with OpenEMS backend.
This filter does not work, since edges by default use the influxdb field "edge" instead of "fems"
=> fixed filter for influxdbv2 query to use edge instead of fems keyword

ui/src/app/edge/settings/systemupdate/systemupdate.component.html, ui/src/app/edge/settings/systemupdate/systemupdate.component.ts
This is an improvement to the current system update feature. Future required tasks include (in German):
- Umbenennen "Update Status ist unbekannt" zu "Suche nach Updates..." (oder ähnlich)
- Nach Klick auf "Update installieren" sollte sofort die Prozentanzeige mit "Update wird ausgeführt" erscheinen
-  Am Anfang springt die Prozentanzeige hin und her
- Die Prüfung auf >= 98 % ist so nicht sinnvoll, da brauchen wir eine andere Logik.
- Im Log für ngx-spinner bekomme ich die folgende Fehlermeldung (auch für andere spinner, z. B. im Live): [ngx-spinner]: Property "type" is missed. Please, provide animation type to <ngx-spinner> component and ensure css is added to angular.json file
"Das System ist auf dem aktuellen Softwarestand" sollten wir deutlicher hervorheben/fett drucken
- Die …
=> Update system update feature

io.openems.edge.timeofusetariff.corrently/src/io/openems/edge/timeofusetariff/corrently/CorrentlyImpl.java
Corrently API has changed the call param zipcode to zip.
New format: https://api.corrently.io/v2.0/gsi/marketdata?zip=80801
=> timeofuse corrently bundle: changed URL parameter from zipcode to zip

io.openems.edge.core/src/io/openems/edge/core/sum/SumImpl.java
Hi @sfeilmeier 
I am implementing a HybridEss and realized that this channel is force calculated. I do have a managed battery that provides this information more precisely, so I would like to not have it calculated. IMO this is not an issue, since you do calculate it the same way here:
https://github.com/OpenEMS/openems/blob/f4b7c7e2aad1487acbdc59597f39bd9ef04ebdad/io.openems.edge.ess.fenecon.commercial40/src/io/openems/edge/ess/fenecon/commercial40/EssFeneconCommercial40Impl.java#L893
This PR is related to an HybridEss Nature Implementation of a Victron Ess (Multiplus 2GX and BlueSolar SolarCharger).
I will open-source the implementation once it works properly.
=> build dcdischarge sum out of hybridess channel instead of plain calculation

io.openems.edge.common/src/io/openems/edge/common/test/DummyComponentManager.java, io.openems.edge.core/src/io/openems/edge/app/api/ModbusTcpApiReadOnly.java, io.openems.edge.core/src/io/openems/edge/app/heat/CombinedHeatAndPower.java, io.openems.edge.core/src/io/openems/edge/app/heat/HeatPump.java, io.openems.edge.core/src/io/openems/edge/app/heat/HeatingElement.java, io.openems.edge.core/src/io/openems/edge/app/integratedsystem/FeneconHome.java, io.openems.edge.core/src/io/openems/edge/app/meter/CarloGavazziMeter.java, io.openems.edge.core/src/io/openems/edge/app/meter/JanitzaMeter.java, io.openems.edge.core/src/io/openems/edge/app/meter/SocomecMeter.java, io.openems.edge.core/src/io/openems/edge/app/pvselfconsumption/GridOptimizedCharge.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/AppManagerImpl.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/AppManagerUtil.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/AppManagerUtilImpl.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/ComponentUtilImpl.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/dependency/AppManagerAppHelperImpl.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/dependency/ComponentAggregateTaskImpl.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/dependency/DependencyUtil.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/validator/CheckCardinality.java, io.openems.edge.core/test/io/openems/edge/app/TestC.java, io.openems.edge.core/test/io/openems/edge/app/api/TestModbusTcpApiReadWrite.java, io.openems.edge.core/test/io/openems/edge/app/integratedsystem/TestFeneconHome.java, io.openems.edge.core/test/io/openems/edge/core/appmanager/AppManagerAppHelperImplTest.java, io.openems.edge.core/test/io/openems/edge/core/appmanager/AppManagerImplTest.java, io.openems.edge.core/test/io/openems/edge/core/appmanager/AppManagerTestBundle.java
Made referencing other Instances more dynamically during installation.
e. g. an Instance that gets currently created now can be referrenced by other Apps that also being created.
Changed Cardinality of Meter to Multiple.
Improved JUnit testing
Picking ID for Components now starts from the number given as the default ID.
=> App Manager

io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/api/ElementToChannelConverter.java
In the previous version, the ElementToChannelConverter KEEP_POSITIVE mapped a value to a converter instead of a new value.
=> ElementToChannelConverter KEEP_POSITIVE fixed

io.openems.edge.simulator/src/io/openems/edge/simulator/meter/grid/acting/GridMeter.java, io.openems.edge.simulator/src/io/openems/edge/simulator/meter/grid/reacting/GridMeter.java
Simulator Grid-Meters Acting and Reacting should ignore Ess-Cluster, otherwise values are applied twice.
See https://community.openems.io/t/fehler-bei-verbrauch-mit-ess-cluster/1133/4
=> Simulator Grid-Meter: Ignore Ess-Cluster

io.openems.edge.common/src/io/openems/edge/common/component/AbstractOpenemsComponent.java, io.openems.edge.common/test/io/openems/edge/common/component/AbstractOpenemsComponentTest.java
See discussion at
https://community.openems.io/t/automatische-komponentenid-in-abstractopenemscomponent/1144
=> OpenemsComponent: do not auto-generate a Component-ID; throw IllegalArgumentException instead

ui/src/app/edge/live/live.component.ts, ui/src/app/index/index.component.html, ui/src/app/index/index.component.ts, ui/src/app/shared/service/websocket.ts, ui/src/assets/i18n/de.json, ui/src/assets/i18n/en.json
1. Separating ExceptionAuthentication Failed (error code 1003) vs. Request Timeout (error code 1); The Session-Token of Cookie should not be deleted for Request Timeout
2. Prevent overload of requestcalls on Login due to multiple clicking on login-button
3. SubscribeEdgesRequest should only be sent if ui is connected to backend - not to edge
Co-authored-by: Lukas Rieger <73471197+lukasrgr@users.noreply.github.com>
Reviewed-by: Stefan Feilmeier <3515268+sfeilmeier@users.noreply.github.com>
=> UI: Login improvements

io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/core/BpCore.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/core/BpCoreImpl.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/core/BpData.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/ess/BpEss.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/ess/BpEssImpl.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/ess/charger/BpCharger.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/ess/charger/BpChargerImpl.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/pvinverter/BpPvInverter.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/pvinverter/BpPvInverterImpl.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/pvinverter/SetPvLimitHandler.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/vectis/Vectis.java, io.openems.edge.kaco.blueplanet.hybrid10/src/io/openems/edge/kaco/blueplanet/hybrid10/vectis/VectisImpl.java
- Errors become clearer visible to the user (not "kacoCore0" failed, but "ess0" failed)
- Pure PV-Inverter is not reachable during night. New structure allows to avoid/delay the error
- Introduce BpData record to merge all DataSet classes from KACO library
=> KACO Bp10: move communication failure to individual components

.github/workflows/build.yml, .github/workflows/docs.yml, build.gradle
* buildEdge : openems.jar -> openems-edge.jar
* split build-code into build-java, build-ui and release
* run build-java and build-ui parallel
* build-java : extend gradle cache
* build-ui :  node-14 -> node-16
* build-ui : add ng cache
* build-ui : use 'zip' to pack ui instead of '7z'
* use actions/checkout@v3
* use gradle cache
=> Improve Github-Workflows

io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/RestHandler.java
Add "value" attribute only if the channel is Readable.
=> REST-Api: handle WRITE_ONLY channels properly (OpenEMS#2025)

io.openems.edge.common/src/io/openems/edge/common/channel/calculate/CalculateAverage.java, io.openems.edge.common/test/io/openems/edge/common/channel/calculate/CalculateAverageTest.java
Hi team,
Thank you for the wonderful project! 
During development I ran into, what seems to me, a bug in the CalculateAverage class.
---
- CalculateAverage::addValue resulted in ClassCastExceptions when the channel was not of type Integer
- This happened because the parameter of the method was Channel<Integer>
- Now supports any implementation of Number
---
Let me know if there is anything I can improve
=> Bug: CalculateAverage now supports all numbers instead of integer

io.openems.edge.timeofusetariff.tibber/bnd.bnd, io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/Config.java, io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/FoundMultipleHomesException.java, io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/Tibber.java, io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/TibberImpl.java, io.openems.edge.timeofusetariff.tibber/src/io/openems/edge/timeofusetariff/tibber/Utils.java, io.openems.edge.timeofusetariff.tibber/test/io/openems/edge/timeofusetariff/tibber/MyConfig.java, io.openems.edge.timeofusetariff.tibber/test/io/openems/edge/timeofusetariff/tibber/TibberImplTest.java, io.openems.edge.timeofusetariff.tibber/test/io/openems/edge/timeofusetariff/tibber/UtilsTest.java
The TIbber API allows accessing multiple 'Homes'. This PR introduces a 'filter' config property, that allows filtering for the correct one. 
Also add State-Channels:
- UnableToUpdatePrices: general HTTP error
- FilterIsRequired: multiple Homes where retreived from the API and it is not possible to identify without filter (i.e. more than one valid 'Home' was parsed)
This fixes #2049
=> Tibber: add filter for multiple 'Homes'

io.openems.edge.meter.sunspec/src/io/openems/edge/meter/sunspec/AbstractSunSpecMeter.java
Energy values were mapped twice in AbstractSunspecMeter, once with the wrong converter.
=> AbstractSunSpecMeter Energy value fix

io.openems.edge.meter.virtual/src/io/openems/edge/meter/virtual/symmetric/add/VirtualAdd.java
a) Consumption Energy is now calculated correctly (remained null before)
b) Min- and max active powers are automatically derived from active power and should not be calculated by the meter. (The sum of the max powers is not necessarily the max power of the sum anyway)
=> Two small bugfixes in VirtualMeterAdd

io.openems.edge.meter.sunspec/src/io/openems/edge/meter/sunspec/AbstractSunSpecMeter.java
As discussed in the previous pull request, energy per phase is added to the abstract sunspec meter.
=> Energy per phase added to AbstractSunSpecMeter

io.openems.edge.controller.ess.fixactivepower/bnd.bnd, io.openems.edge.controller.ess.fixactivepower/src/io/openems/edge/controller/ess/fixactivepower/Config.java, io.openems.edge.controller.ess.fixactivepower/src/io/openems/edge/controller/ess/fixactivepower/EssFixActivePowerImpl.java, io.openems.edge.controller.ess.fixactivepower/src/io/openems/edge/controller/ess/fixactivepower/HybridEssMode.java, io.openems.edge.controller.ess.fixactivepower/test/io/openems/edge/controller/ess/fixactivepower/EssFixActivePowerImplTest.java, io.openems.edge.controller.ess.fixactivepower/test/io/openems/edge/controller/ess/fixactivepower/MyConfig.java, io.openems.edge.ess.api/src/io/openems/edge/ess/test/DummyHybridEss.java
Add a configuration setting `hybridEssMode`, that allows defining the DC-side power set-point
=> ESS Fix Active Power: handle Hybrid-ESS

io.openems.edge.pvinverter.fronius/src/io/openems/edge/pvinverter/fronius/Config.java, io.openems.edge.pvinverter.fronius/src/io/openems/edge/pvinverter/fronius/FroniusPvInverter.java, io.openems.edge.pvinverter.kaco.blueplanet/bnd.bnd, io.openems.edge.pvinverter.kaco.blueplanet/src/io/openems/edge/pvinverter/kaco/blueplanet/Config.java, io.openems.edge.pvinverter.kaco.blueplanet/src/io/openems/edge/pvinverter/kaco/blueplanet/KacoBlueplanet.java, io.openems.edge.pvinverter.kaco.blueplanet/test/io/openems/edge/pvinverter/kaco/blueplanet/KacoBlueplanetTest.java, io.openems.edge.pvinverter.kaco.blueplanet/test/io/openems/edge/pvinverter/kaco/blueplanet/MyConfig.java, io.openems.edge.pvinverter.kostal/src/io/openems/edge/pvinverter/kostal/Config.java, io.openems.edge.pvinverter.kostal/src/io/openems/edge/pvinverter/kostal/KostalPvInverter.java, io.openems.edge.pvinverter.kostal/test/io/openems/edge/pvinverter/kostal/KostalPvInverterTest.java, io.openems.edge.pvinverter.kostal/test/io/openems/edge/pvinverter/kostal/MyConfig.java, io.openems.edge.pvinverter.sma/bnd.bnd, io.openems.edge.pvinverter.sma/src/io/openems/edge/pvinverter/sma/Config.java, io.openems.edge.pvinverter.sma/src/io/openems/edge/pvinverter/sma/SmaPvInverter.java, io.openems.edge.pvinverter.sma/test/io/openems/edge/pvinverter/sma/MyConfig.java, io.openems.edge.pvinverter.sma/test/io/openems/edge/pvinverter/sma/SmaPvInverterTest.java, io.openems.edge.pvinverter.sunspec/src/io/openems/edge/pvinverter/sunspec/AbstractSunSpecPvInverter.java, io.openems.edge.pvinverter.sunspec/src/io/openems/edge/pvinverter/sunspec/SetPvLimitHandler.java, io.openems.edge.pvinverter.sunspec/src/io/openems/edge/pvinverter/sunspec/SunSpecPvInverter.java, io.openems.edge.solaredge/src/io/openems/edge/solaredge/pvinverter/Config.java, io.openems.edge.solaredge/src/io/openems/edge/solaredge/pvinverter/SolarEdgePvInverter.java, io.openems.edge.solaredge/test/io/openems/edge/solaredge/pvinverter/MyConfig.java, io.openems.edge.solaredge/test/io/openems/edge/solaredge/pvinverter/SolarEdgePvInverterTest.java
Currently all `ManagedSymmetricPvInverter`s set the power limitation - even if in most cases this is not required, because no PV-Limit controller is active. In these cases currently a power limit to 100 % is set via Modbus (i.e. 'no limit'). PV-Inverters often distinguish between Modbus read-only and read/write access. The current behaviour causes Modbus errors if write-access to the PV inverter is not allowed.
This PR adds a new 'readOnly' setting that is activated by default. The idea of a 'read-only mode' is already existing in other places in OpenEMS for such use cases. In 'read-only mode' no PV limit is ever written. If there is a demand for pv limit anyway (e.g. via a `Controller.PvInverter.FixPowerLimit`), then a warning "Read-Only mode is active: PV-Limit failed" (Channel-ID: …
=> PV-Inverters: add read-only mode

io.openems.edge.common/src/io/openems/edge/common/channel/internal/AbstractReadChannel.java
Channel `nextProcessImage()` should not throw an Exception. Currently an IllegalArgumentException on updating of the process image is handled only very late, e.g. in the CycleWorker. This improvement catches the error early in the Channel itself and prints detailed error logs.
=> Channel: catch errors while updating Process-Image

io.openems.edge.meter.api/src/io/openems/edge/meter/api/SinglePhaseMeter.java, io.openems.edge.meter.sunspec/src/io/openems/edge/meter/sunspec/AbstractSunSpecMeter.java, io.openems.edge.pvinverter.sunspec/src/io/openems/edge/pvinverter/sunspec/AbstractSunSpecPvInverter.java
Applies to
- PV-Inverter.Fronius
- PV-Inverter.KACO.blueplanet
- PV-Inverter.Kostal
- PV-Inverter.SMA.SunnyTripower
- SolarEdge.PV-Inverter
Improvements:
- Set individual phases power, current & voltage for new `ElectricityMeter`
- Evaluate more blocks (= improves device compatibility)
- Code cleanup
=> SunSpec PV-Inverters + Meters: improve implementation

ui/src/app/app.component.ts, ui/src/app/edge/settings/settings.component.html, ui/src/app/edge/settings/settings.component.ts
Because not all angular events are firing, when they should, this globalRouteChangeHandler was introduced. Its possible to pass the pagetitle to [routes](https://github.com/OpenEMS/openems/blob/36483e70875e4d92a9a65ca15ba2ebf656817345/ui/src/app/app-routing.module.ts#L52). 
This is also a first step, to avoid setting currentPagetitle with every component.
If you don't know, what is meant with this take a look here: 
[openems-edge-dev](https://github.com/OpenEMS/openems/blob/develop/ui/src/themes/openems/environments/edge-dev.ts) and here [README](https://github.com/OpenEMS/openems/blob/develop/ui/README.md)
=> UI: Inject globalRouteChangeHandler

io.openems.edge.evcs.hardybarth/src/io/openems/edge/evcs/hardybarth/EvcsHardyBarthImpl.java, io.openems.edge.evcs.hardybarth/src/io/openems/edge/evcs/hardybarth/HardyBarthReadWorker.java, io.openems.edge.evcs.hardybarth/test/io/openems/edge/evcs/hardybarth/EvcsHardyBarthImplTest.java
Some evcs had less than 300mA on one or two phases, even though it was charging on all three phases.
Another Hardy Barth was returning null for status for an unknown reason, so a debounce was added.
=> EVCS: Improve HardyBarth phase and status detection.

io.openems.common/src/io/openems/common/channel/Unit.java, io.openems.common/src/io/openems/common/utils/EnumUtils.java, io.openems.edge.battery.bydcommercial/src/io/openems/edge/battery/bydcommercial/BydBatteryBoxCommercialC130Impl.java, io.openems.edge.battery.fenecon.commercial/src/io/openems/edge/battery/fenecon/commercial/BatteryFeneconCommercialImpl.java, io.openems.edge.battery.fenecon.home/src/io/openems/edge/battery/fenecon/home/BatteryFeneconHomeImpl.java, io.openems.edge.battery.fenecon.home/src/io/openems/edge/battery/fenecon/home/statemachine/GoRunningHandler.java, io.openems.edge.battery.soltaro/src/io/openems/edge/battery/soltaro/cluster/versionc/BatterySoltaroClusterVersionCImpl.java, io.openems.edge.battery.soltaro/src/io/openems/edge/battery/soltaro/single/versionb/BatterySoltaroSingleRackVersionBImpl.java, io.openems.edge.battery.soltaro/src/io/openems/edge/battery/soltaro/single/versionc/BatterySoltaroSingleRackVersionCImpl.java, io.openems.edge.batteryinverter.kaco.blueplanetgridsave/src/io/openems/edge/batteryinverter/kaco/blueplanetgridsave/BatteryInverterKacoBlueplanetGridsaveImpl.java, io.openems.edge.batteryinverter.refu88k/src/io/openems/edge/batteryinverter/refu88k/BatteryInverterRefuStore88kImpl.java, io.openems.edge.batteryinverter.sinexcel/src/io/openems/edge/batteryinverter/sinexcel/BatteryInverterSinexcelImpl.java, io.openems.edge.common/src/io/openems/edge/common/statemachine/AbstractStateMachine.java, io.openems.edge.common/src/io/openems/edge/common/statemachine/StateHandler.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/common/AbstractGenericManagedEss.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/offgrid/EssGenericOffGridImpl.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/symmetric/EssGenericManagedSymmetricImpl.java, io.openems.edge.fenecon.mini/src/io/openems/edge/fenecon/mini/ess/FeneconMiniEssImpl.java
This improvement enables better insight into State-Machines at runtime, by providing a convenience method for logging the current state of a State-Machine. It is especially useful if more info than just the name of the State is useful to be logged.
Also we update the debugLog() implementations to use StringBuilder, which has better performance than string concatenation.
=> State-Machine: add debugLog functionality

doc/modules/ROOT/pages/contribute/coding-guidelines.adoc
Current "Code Contribution Guidelines" documentation refer to the "Java" code formatter. The documentation should be switched to suggest the "Eclipse [built in]" code formatter.
Reason 1: Most of the code is already checked in with the  "Eclipse [built in]" code formatter.
Reason 2: the  "Eclipse [built in]" code formatter is the default code formatter when starting a new eclipse project. Less configuration lowers the barrier for newcomers to immediately start with programming.
=> change contribution doc to describe "Eclipse [built in]" code formatter

io.openems.edge.meter.api/src/io/openems/edge/meter/api/ElectricityMeter.java
In calculateSumActiveProductionEnergyFromPhases() wrong channels were used.
Additionally it caused a null pointer, when the result would have been null, because it was internally trying to call intValue() to parse it into a long.
=> ElectricityMeter: Use correct channels and avoid null pointer.

io.openems.edge.common/src/io/openems/edge/common/type/TypeUtils.java, io.openems.edge.meter.virtual/src/io/openems/edge/meter/virtual/add/AddChannelManager.java, io.openems.edge.meter.virtual/test/io/openems/edge/meter/virtual/add/MeterVirtualAddImplTest.java
New pull request after applying changes to latest version of OpenEMS. Closing original PR #2166
The average channel value for channels such as frequency and voltage was incorrectly calculated. Instead of taking the average of all channel values the average was computed as follows. 
Example based on the adjusted test case for voltage:
**old:** avg(avg(avg(null, 10), 20), 30) == 22.5 ❌
**new** avg(10, 20, 30) == 20 ✅
The test case has also been adjusted surface the problem without the fix and pass correctly with the new code.
@sfeilmeier, hope this addresses your concerns in #2166
=> Virtual meter bug fix: average is computed correctly

io.openems.edge.common/src/io/openems/edge/common/channel/AbstractChannelListenerManager.java
As discussed in issue: https://github.com/OpenEMS/openems/issues/2302
=> AbstractChannelListenerManager: clean up unused listeners after deactivate()

ui/src/app/index/index.component.ts
- Adds a check for OpenEMS Edge as backend, to be getting redirected to live-view
Solves this community Issue: https://community.openems.io/t/2023-8-ui-bleibt-nach-login-hangen/1837/4
=> UI: Add redirection for 'OpenEMS Edge' as backend

ui/src/app/edge/live/Controller/Evcs/modal/modal.html, ui/src/app/shared/service/utils.ts
* Correcting color in storage icon of evcs modal from ```primary``` to ```success```
* Avoiding infinity sign in production history flat widget
=> UI: Change color of storage icon in evcs modal

io.openems.edge.battery.api/src/io/openems/edge/battery/test/DummyBattery.java, io.openems.edge.batteryinverter.api/src/io/openems/edge/batteryinverter/test/DummyManagedSymmetricBatteryInverter.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/common/AbstractChannelManager.java, io.openems.edge.ess.generic/src/io/openems/edge/ess/generic/common/AbstractGenericManagedEss.java, io.openems.edge.ess.generic/test/io/openems/edge/ess/generic/symmetric/EssGenericManagedSymmetricImplTest.java
Due to a sign flaw the allowed max charge power was shown wrongly, i.e. if battery says "-56000" and battery-inverter "-92000", it would show "-92000". Fixed and proven with JUnit test
Also: add listener to execute `allowedChargeDischargeHandler` also if ESS StartStop changes.
=> Generic-Ess: fix debugLog for max charge power

io.openems.edge.bridge.modbus/readme.adoc
as mentioned in https://community.openems.io/t/error-of-link-in-tutorials/1894
=> Modbus Bridge: fix typo in README

io.openems.edge.bridge.modbus/src/io/openems/edge/bridge/modbus/sunspec/AbstractOpenemsSunSpecComponent.java
This PR solves issue #2311. Similar to the Edge2Edge-component, if a modbus task is longer than the limit of j2mod (= 126), it is split. 
Note: When adding a JUnit test to see if it is working (I created a Dummy SunSpec Component which uses all default SunSpec models), I found an error in the `AbstractOpenemsSunSpecComponent`, namely that channels with a constant scale factor (e.g. S305_LAT) are not working. I will treat this in a seperate PR, which will also include my small JUnit test.
=> Modbus SunSpec: split modbus tasks with more than 126 registers

io.openems.backend.common/src/io/openems/backend/common/edgewebsocket/EdgeWebsocket.java, io.openems.backend.common/src/io/openems/backend/common/uiwebsocket/UiWebsocket.java, io.openems.backend.edgewebsocket/src/io/openems/backend/edgewebsocket/EdgeWebsocketImpl.java, io.openems.backend.edgewebsocket/src/io/openems/backend/edgewebsocket/SystemLogHandler.java, io.openems.backend.uiwebsocket/src/io/openems/backend/uiwebsocket/impl/OnRequest.java, io.openems.backend.uiwebsocket/src/io/openems/backend/uiwebsocket/impl/UiWebsocketImpl.java, io.openems.backend.uiwebsocket/src/io/openems/backend/uiwebsocket/impl/WsData.java
System log was only send to one UI when mulitple UIs of the same user were opened.
added unique id for each websockte connection
replaced subscribe with token to ui websocket id
=> Backend: fix subscribe system log

io.openems.backend.uiwebsocket/src/io/openems/backend/uiwebsocket/impl/OnRequest.java
=> Backend: UI-Websocket: get user.globalRole instead of default guest role on AlertingConfigs

ui/src/app/edge/live/Controller/Evcs/modal/modal.html
In the past automatic mode used the sunny-outline icon.
This is missing here (idk if it was intentional).
=> UI: evcscontroller -> automatic mode -> uses sunny-icon again

ui/.vscode/extensions.json, ui/.vscode/settings.json
=> fix: specify eslint as vscode workspace default formatter

doc/tools/create_single_page_html.sh, doc/tools/create_single_page_pdf.sh
This PR changes reparing single document generating shell script and supporting nav.adoc-based single document generation without management single_document.adoc
background:
Occording history of git-log, there was single_document.adoc to generate single page document output, but currently is not. so create_single_page_{pdf, html}.sh fails.
// I and ikegam guessed the reason is avoiding duplication of managing nav.adoc and single_document doc. because almost user mainly use multiple page document(based-on nav.adoc) on webui.
idea:
Therefore We forcus to difference nav.adoc and single_document.adoc and plant to re-use nav.adoc as single_documet.adoc by using sed because there are only little difference.
This commit is maded by multiple contributors
=> fix: reproduce single_document.adoc from nav.adoc and sed script

io.openems.backend.metadata.dummy/src/io/openems/backend/metadata/dummy/MetadataDummy.java
By default the filter is an empty list, which caused zero results. See Community posts:
- https://community.openems.io/t/openems-backend-not-showing-anything-in-ui/1979/4
- https://community.openems.io/t/getting-started-problem-when-adding-the-backend-metadata-related/2116/4
=> Metadata Dummy: fix filter for product types

ui/src/app/shared/type/language.ts
US English browsers report language as `en-US`.  Because this wasn't handled in the switch statement, the application falls back to the default language.
=> Handle en-US language for US browsers

doc/modules/ROOT/pages/edge/implement.adoc
There was a small formatting error in section the 1.4. Implement the OpenEMS Component and the wrong button name in section 1.7. Enable the Component.
=> Minor corrections to the edge component implementation guide

doc/modules/ROOT/pages/contribute/coding-guidelines.adoc
Different Eclipse IDE versions produces different source files, when using autoformat, cleanup,.... Also they produce different warnings. Therefore it would be important, that all developers always use the same eclipse version before opening new PRs. 
This PR adds a documentation section to the contribution guidelines to always use the latest Eclipse version. By the time of now this is version 2023-12 (4.30.0)
=> Docs: Contribution Guidelines: add section about Eclipse Version

ui/src/app/edge/settings/component/install/index.component.ts, ui/src/app/edge/settings/component/update/index.component.ts
When entering CamelCased / Uppercase entries in the search bar of component install/update -> the components won't show/cannot be found since the filter is CaseSensitive, while the filteredComponents are not.
see :
https://github.com/OpenEMS/openems/blob/2c938aab7a19407e6ab5dcac7b33c5e15da971df/ui/src/app/edge/settings/component/update/index.component.ts#L49-L55
set filter to lowerCase
Co-authored-by:  Ulrich Laupp  <38915524+laupp@users.noreply.github.com>
=> UI: Install/Update Component filter to lower case

ui/src/app/shared/genericComponents/modal/modal-line/modal-line.html, ui/src/app/shared/genericComponents/modal/modal-line/modal-line.ts
Implements a new modal-line element INPUT_UNIT. It's the similar to INPUT with the option to change the unit with the following code line. 
eg: [control]="{type: 'INPUT_UNIT', properties: {unit: 'mA'}}">
=> UI: modal-line element INPUT with optional unit

io.openems.edge.meter.janitza/src/io/openems/edge/meter/janitza/umg511/MeterJanitzaUmg511Impl.java
Previously, the overall active power was not inverted if configured, only the phase powers were. This is fixed here.
=> Janitza UMG 511: fix inverted active power

doc/modules/ROOT/pages/contribute/coding-guidelines.adoc, doc/modules/ROOT/pages/edge/implement.adoc
Added the Case to test only the Module on which you are working on.
./gradlew :io.openems.edge.ess.sungrow:clean for example - it leads to a faster building/testing Time
=> Docs: update implementing a device

io.openems.common/src/io/openems/common/websocket/AbstractWebsocketClient.java, io.openems.common/src/io/openems/common/websocket/AbstractWebsocketServer.java
This PR changes websocket communication use compression.
cf.
- https://datatracker.ietf.org/doc/html/rfc7692
- https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/PerMessageDeflateExample.java
=> WebSocket: enable permessage-deflate to communication

build.gradle
For some build processes the xml file is better integrated (e.g. if you need to transform the jacoco report to a cobertura report). So far only the csv report was generated.
=> Generate jacoco xml report

build.gradle
The build fails because `io.openems.oem.openems` is not included as a dependency in `./gradlew :buildEdge`. I have updated `build.gradle` to include `io.openems.oem.openems` to resolve this issue.
```
$ ./gradlew clean && ./gradlew :buildEdge
[snip]
> Task :io.openems.edge.application:resolve.EdgeApp FAILED
Resolution failed. Capabilities satisfying the following requirements could not be found:
[<<INITIAL>>]
⇒ osgi.identity: (osgi.identity=io.openems.edge.controller.api.backend)
⇒ [io.openems.edge.controller.api.backend version=1.0.0.202405210545]
⇒ osgi.service: (objectClass=io.openems.common.oem.OpenemsEdgeOem)
[slf4j.api__0 version=1.8.0.beta4 type=bnd.synthetic]
⇒ osgi.ee: (&(osgi.ee=JavaSE)(&(version>=0.0.0)(!(version>=9.0.0))))
[org.jsoup__8 version=1.17.2 type=bnd.synthetic]
⇒ …
```
=> fix: ./gradlew buildEdge error

build.gradle, tools/docker/backend/Dockerfile, tools/docker/edge/Dockerfile, tools/docker/ui/Dockerfile, tools/docker/ui/index.patch, ui/src/index.html
Current openems-ui Docker images do not work because the env.js file is missing.
=> Fix docker ui builds

ui/.eslintrc.json, ui/src/app/edge/settings/system/maintenance/maintenance.ts, ui/src/app/edge/settings/system/oe-system-update.component.ts, ui/src/app/shared/genericComponents/modal/modal-button/modal-button.ts, ui/src/app/shared/genericComponents/shared/oe-formly-component.ts, ui/src/app/shared/service/service.ts
1. banned using Object, Function types
2. refactor .eslintrc
=> Update eslint rules and refactoring types.

io.openems.edge.scheduler.allalphabetically/test/io/openems/edge/scheduler/allalphabetically/SchedulerAllAlphabeticallyImplTest.java
While figuring out how the alphabetical scheduler orders controller ids, I wrote this unit test. It's not changing anything, but just adding additional tests with a wider range of scheduler ids.
=> Unit Tests: Add test case for alphabetical scheduler

ui/src/app/changelog/view/component/changelog.constants.ts, ui/src/app/edge/history/historydataservice.ts, ui/src/app/edge/live/Controller/Ess/TimeOfUseTariff/flat/flat.ts, ui/src/app/edge/live/Controller/Ess/TimeOfUseTariff/modal/modal.ts, ui/src/app/edge/live/Multiple/Evcs_Api_Cluster/modal/evcs-chart/evcs.chart.ts, ui/src/app/edge/live/energymonitor/chart/section/abstractsection.component.ts, ui/src/app/shared/components/pickdate/pickdate.component.ts, ui/src/app/shared/service/arrayutils.ts, ui/src/app/shared/service/myerrorhandler.ts, ui/src/app/shared/service/service.ts, ui/src/app/shared/service/test/dummyservice.ts, ui/src/app/shared/service/utils.ts, ui/src/app/shared/type/language.ts, ui/src/app/shared/utils/array/array.utils.ts, ui/src/zone-flags.ts
```
$ vi .eslintrc
drop        "@typescript-eslint/no-explicit-any": 0,
$ npx eslint src/
165 problems (165 errors, 0 warnings)
↓
121 problems (121 errors, 0 warnings)
```
=> fix: decrease using type of any to get typing benefit

io.openems.edge.ess.api/src/io/openems/edge/ess/api/ManagedSymmetricEss.java
Documentation stated that both allowed charge and discharge power are `<= 0`.
=> Fix documentation for allowed charge power of managed symmetric ess

ui/src/app/edge/history/common/energy/chart/channels.spec.ts, ui/src/app/edge/history/common/energy/chart/chart.constants.spec.ts, ui/src/app/shared/components/edge/edgeconfig.spec.ts, ui/src/app/shared/components/shared/testing/tester.ts, ui/src/app/shared/utils/array/array.utils.ts, ui/src/app/shared/utils/date/dateutils.spec.ts
```
$ npx tsc --strict
Found 3646 errors in 210 files.
↓
Found 1492 errors in 211 files.
```
=> fix: add type to test code

ui/src/app/shared/components/edge/edgeconfig.ts, ui/tsconfig.json
npx tsc --strict: 3646 -> 3622 errors
=> fix: add types to edgeconfig.ts

ui/src/app/shared/components/edge/edgeconfig.ts
This pull request offers two alternative solutions to fix the issue in the `listActiveComponents` method. 
```typescript
components.push(...this.getComponentsByFactory(factory.id));
```
In this approach, we use the `push` method to add elements to the `components` array directly. 
- **Simplicity**: The code is straightforward and easy to understand.
- **Performance**: `push` modifies the array in place, which is generally faster than creating a new array with `concat`.
- **In-Place Modification**: `push` modifies the original array, which might not be desirable if you need to maintain immutability.
```typescript
public listActiveComponents(ignoreComponentIds: string[] = []): CategorizedComponents[] {
const allComponents = [];
const factories = this.listAvailableFactories();
for (const …
```
=> Fix for Configuration & Status not populated Fully

tools/docker/backend/README.md, tools/docker/edge/README.md
This is just a small commit that should help people trying to build their own Docker image. When running the build command from the readme file the error `failed to solve: error from sender: context canceled` can occur. This can easily be fixed by making sure the Eclipse IDE isn't open. To avoid others having to search for a solution I would like to add this info to the readme.
=> Add hint to README to fix an error with building a Docker image

build.gradle, cnf/checkstyle.xml, io.openems.edge.controller.ess.gridoptimizedcharge/test/io/openems/edge/controller/ess/gridoptimizedcharge/ControllerEssGridOptimizedChargeImplTest.java
See https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-10.18.2 for details.
Unfortunately Checkstyle by default requires _no_ newline after `<p>` in JavaDoc, whereas Eclipse IDE automatically adds one by default. This is PR disables this check.
=> Update Checkstyle to 10.18.2

ui/src/app/shared/components/header/header.component.html
ion-segment itself already manages a group of buttons (ion-segment-button elements). By removing the redundant <ion-buttons> wrapper, it could simplify the DOM structure, making code cleaner.
=> fix: Delete the duplicate button

io.openems.edge.core/src/io/openems/edge/core/host/HostImpl.java, io.openems.edge.core/src/io/openems/edge/core/host/OperatingSystemMac.java
Added the ability for OpenEMS edge to run on MacOS. Purely to be used for development purposes. The implementation of OperatingSystemMacOS is based on the Windows version.
=> Feature/Dummy MacOS Support

io.openems.edge.ess.api/src/io/openems/edge/ess/dccharger/api/EssDcCharger.java
The hash of EssDcCharger devices on the Modbus interface currently incorrectly identifies them as SymmetricEss. This PR fixes the problem by replacing the incorrect class passed to the ModbusSlaveNatureTable.of method.
=> Fix EssDcCharger nature on modbus

ui/src/app/index/filter/filter.component.html, ui/src/global.scss
This PR addresses the styling issues in the filter component following the migration to Angular 19. The update ensures that the filter element now properly adheres to the desired styling, improving its appearance and functionality.
- Updated the `ion-select` component's attributes in `filter.component.html`:
- Removed the redundant `fill="solid"` and `fill="outline"` attributes.
- Corrected the usage of `ion-select` to ensure the correct styling for the popover interface.
Before:
After:
- After the migration to Angular 19, certain style configurations were causing issues in how the filter component was displayed. Specifically, conflicting properties like `fill="solid"` and `fill="outline"` were causing style misalignment and preventing the filter from displaying correctly.
- This fix …
=> Fix Filter Style after Migration to Angular 19

ui/src/app/edge/settings/systemlog/systemlog.component.html
This PR addresses the styling issues related to the "Level" `ion-select` component after the upgrade to Angular 19. The update resolves issues with the component's appearance, ensuring it aligns with the expected UI standards.
- Corrected the configuration and attributes of the "Level" `ion-select` in `systemlog.component.html`.
- Removed duplicate `ion-select` tags and conflicting attributes.
- Ensured the proper `fill`, `label`, and `interface` attributes are applied to maintain consistent styling.
- Fixed label positioning and `interfaceOptions` for the custom styling of the popover.
Before:
AfteR:
- Following the upgrade to Angular 19, some `ion-select` components, particularly the "Level" selection dropdown, were displaying incorrectly due to conflicting properties and misapplied …
=> Fix Style of Level ion-select after Upgrade to Angular 19

ui/src/environments/index.ts, ui/src/themes/openems/environments/backend-dev.ts, ui/src/themes/openems/environments/backend-prod.ts, ui/src/themes/openems/environments/edge-dev.ts, ui/src/themes/openems/environments/edge-prod.ts
Prevents mixed content errors in the browser by selecting WSS or WS for the websocket depending on the page's scheme (HTTPS or HTTP).
This fixes the problem described in [issue 2396](https://github.com/OpenEMS/openems/issues/2936).
=> Websocket: WSS instead of WS if page is accessed via HTTPS

ui/src/app/app.module.ts, ui/src/app/edge/history/abstracthistorychart.ts, ui/src/app/edge/history/storage/singlechart.component.ts, ui/src/app/edge/history/storage/totalchart.component.ts, ui/src/app/edge/live/Controller/Ess/TimeOfUseTariff/modal/powerSocChart.ts, ui/src/app/edge/live/Controller/Ess/TimeOfUseTariff/modal/statePriceChart.ts, ui/src/app/edge/live/common/storage/storage.component.ts, ui/src/app/edge/settings/powerassistant/powerassistant.ts, ui/src/app/shared/components/chart/abstracthistorychart.ts, ui/src/app/shared/components/flat/abstract-flat-widget.ts, ui/src/app/shared/components/modal/modal-phases/modal-phases.ts, ui/src/app/shared/components/shared/testing/tester.ts, ui/src/app/shared/service/utils.ts
Locale is depends on locale(tautology). but current openems-ui code is using `de` as hardcoding. This PR add mecanizm for locale determining by user environment.
- formatNumber is pure function, no state. so locale need to be specified by argument. In this change I added `locale` argument to utility functions and set LOCALE_ID as `utility` argument in caller.
- In angular global locale context is in root module provider so it is difficult to change from function calling from outside.  In this change I changed LOCAL_ID provider initialization from `useValue` to `useFactory`. Factory function use localstorage language setting currently because language and locale is not clearly separated.
- I don't understand testing code well, so for now, I just added `de` to testing function calling …
=> feat: dynamic numberformat conversion by using current locale

ui/src/app/index/overview/overview.component.html
This PR updates the search functionality in the `overview.component.html` by modifying the event that triggers the search action when the user types in the `ion-searchbar`. 
- Replaced the `(ionChange)` event with the `(input)` event on the `ion-searchbar`. 
- This change ensures that the `searchOnChange()` method is called immediately when the input value changes, allowing the search to trigger as the user types, rather than only after pressing enter or losing focus.
- The `(ionChange)` event would only fire when the input field loses focus or the user presses the Enter key. This made the search feel unresponsive for real-time input. By using `(input)`, the search updates dynamically with every keystroke.
- This change enhances the user experience by providing immediate feedback on …
=> UI: Overview search: trigger on every input change

ui/src/global.scss
Before:
After:
Issue:
In some ways the Text overwrites the input container (See Delay before TX):
This change is just an example for a "Quick Fix"
=> Fix component.update View

ui/src/app/shared/components/formly/form-field.wrapper.html, ui/src/app/shared/components/formly/form-field.wrapper.ts, ui/src/app/shared/components/formly/input.html, ui/src/app/shared/components/formly/input.ts, ui/src/app/user/user.component.html
follow up to: #2958 
**Changes**
fixing styles permanently for `component-update` and `component-install` and all other components, which are using the default formlyfield type `input`
=> UI: fix formly form styles

ui/src/app/edge/settings/component/install/index.component.html
This PR updates the `<ion-searchbar>` event from `(ionChange)` to `(ionInput)`. By listening to each keystroke, the filter is applied in real-time as the user types. This delivers immediate feedback on search queries, which can enhance the overall user experience for quick lookups or rapidly changing query inputs.
**Why This Makes More Sense**  
1. **Real-Time Results**: Users see the updated list as they type, making searches feel more interactive and giving them instant feedback.  
2. **Improved UX for Quick Searches**: When dealing with smaller data sets or faster filter operations, immediate updates can be more intuitive than having to confirm or leave the input field first.  
3. **Common Pattern in Live Searches**: Many search experiences provide real-time suggestions or filtering, …
=> Switch from `ionChange` to `ionInput` for Real-Time Filtering in Search Bar

io.openems.edge.core/src/io/openems/edge/core/componentmanager/EdgeConfigWorker.java
Fix java.lang.VerifyError: Inconsistent stackmap frames at branch target 273 that appeared after #2976.
I don't know why, but this fixes the problem.
See #2984
=> Fix VerifyError in EdgeConfigWorker

.github/workflows/build.yml, build.gradle
It adds a new Gradle Plugin named JacocoLog. This plugin prints the instruction coverage to stdout.
We have a GitLab Pipeline without using codecov Bot. GitLab is able to directly consume the code coverage from the stdout of the build job. As we think this feature is useful for others, we wanted to share this contribution. It also mitigates an eventual future merge conflict in out fork.
=> Aggregated coverage report without using codecov

io.openems.backend.common/src/io/openems/backend/common/metadata/User.java
When access is denied due to missing role privileges, currently the desired role is added to the error message. However, the error message indicates that the current user role is printed.
=> fix(backend): display user role as desired by message

io.openems.edge.bridge.http/src/io/openems/edge/bridge/http/api/UrlBuilder.java, io.openems.edge.controller.api.rest/bnd.bnd, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/AbstractRestApi.java, io.openems.edge.controller.api.rest/src/io/openems/edge/controller/api/rest/RestHandler.java, io.openems.edge.controller.api.rest/test/io/openems/edge/controller/api/rest/DummyRestApi.java, io.openems.edge.controller.api.rest/test/io/openems/edge/controller/api/rest/RestHandlerTest.java, io.openems.edge.controller.api.rest/test/io/openems/edge/controller/api/rest/readonly/ControllerApiRestReadOnlyImplTest.java
This PR fixes an issue with square brackets in URLs that was causing HTTP 400 errors. By implementing a more robust URI parsing method and configuring Jetty to use `UriCompliance.UNAMBIGUOUS`, the API now correctly handles URIs containing square brackets for regex patterns.
**Key changes:**
- Configure Jetty server with `UriCompliance.UNAMBIGUOUS` as Compliance mode that allows all unambiguous violations.
- Implement special path parsing to preserve bracket patterns
- Add proper error handling for invalid regex patterns
- Fix favicon.ico handling to prevent authentication errors
- Add test cases for URLs with square brackets
This allows patterns like `/rest/channel/charger[01]/[A-Z].*` to work correctly.
=> Fix handling of URLs with square brackets in Jetty Rest API

io.openems.edge.energy/test/io/openems/edge/energy/optimizer/app/RunOptimizerFromLogApp.java
This PR updates the documented systemd journal extraction command in the `RunOptimizerFromLogApp` to make it more precise and aligned with current usage.
- **Enhanced Log Filtering**: Added a `sed` command to filter log lines so that output always starts with `OPTIMIZER`.
```bash
journalctl -lu openems --since="20 minutes ago" | grep OPTIMIZER
```
```bash
journalctl -lu openems --since="10 minutes ago" | grep OPTIMIZER | sed 's/.*OPTIMIZER/OPTIMIZER/'
```
The change:
- Ensures that the output is cleaner and focused by removing unnecessary log prefixes, making it easier to use the log data for simulation or debugging.
- Verified that the new command returns only the relevant log entries starting with `OPTIMIZER`.
- Confirmed that the updated time window captures the intended log entries …
=> Update Documentation for Log Extraction Command

io.openems.edge.predictor.similardaymodel/readme.adoc, io.openems.edge.predictor.similardaymodel/src/io/openems/edge/predictor/similardaymodel/Config.java, io.openems.edge.predictor.similardaymodel/src/io/openems/edge/predictor/similardaymodel/PredictorSimilardayModelImpl.java, io.openems.edge.predictor.similardaymodel/test/io/openems/edge/predictor/similardaymodel/PredictorSimilardayModelImplTest.java
Fix `ArrayIndexOutOfBoundsException` in SimilarDayPredictor on summer/winter time changeover. Due to time changeover the array of data includes either 4 entries more (summer-> wintertime) or 4 entries less (winter-> summertime).
Cleanup Code for better readability.
Note that I would prefer to remove `_sum/ProductionActivePower` from the default configuration as this predictor is not useful for PV production. On the other hand, this configuration makes it easier for new users to get started.
=> SimilarDayPredictor: Fix ArrayIndexOutOfBoundsException due to time changeover

tools/docker/backend/docker-compose.yml
As docker was complaining:
WARN[0000] docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
cf: https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete
=> Update docker-compose.yml: removed "version" attribute

codecov.yml, io.openems.edge.goodwe/src/io/openems/edge/goodwe/ess/GoodWeEssImpl.java, io.openems.edge.goodwe/test/io/openems/edge/goodwe/ess/GoodWeEssImplTest.java
The old implementation simply said "There is no surplus power, when the SOC is below 99%, and otherwise, the whole production is surplus power". The existing implementation has two weaknesses:
1. You will effectively lose 1-2% of the battery capacity.
2. When the battery is below 99%, but cannot charge for other reasons (e.g. due to low cell temperature), the production power does not count as surplus power, meaning that the controller surplus feed-to-grid would curtail the PV.
The new implementation takes the more generic approach that the surplus power is the production power that cannot be fed into the battery (for whatever reason). It can also be applied for other Hybrid-ESSs.
=> ESS GoodWe: Improved implementation of getSurplusPower()

io.openems.common/src/io/openems/common/jscalendar/JSCalendar.java, io.openems.common/test/io/openems/common/jscalendar/JSCalendarTest.java
Previously, a `NullPointerException` was thrown when parsing a `JSCalendar`-Entry without a recurrence rule. This is fixed here, and JUnit tests are added.
=> Fix JSCalendar without recurrence rule

tools/docker/backend/root/etc/s6-overlay/s6-rc.d/svc-openems-backend/run
Binding to localhost when running on Docker means the Apache Felix web console will only be accessible from inside the docker container, not from the host machine or other containers. This is almost certainly unintended and also conflicts with the provided docker-compose.yml, which suggests exposing the web console port. However, this will not work with the current configuration of felix.
=> Do not bind felix http host to localhost in docker backend

io.openems.edge.core/src/io/openems/edge/core/appmanager/AppManager.java, io.openems.edge.core/src/io/openems/edge/core/appmanager/ResolveOpenemsHardware.java, io.openems.edge.core/test/io/openems/edge/core/appmanager/ResolveOpenemsHardwareTest.java
Fixed a typo in the _appManager/HardwareMissmatch (mismatch instead of missmatch) channel name. Since this a channel name, not sure if it is easy enough to be fixed and what potential external dependencies are.
Feel free to close this PR if a fix would be able to break external code.
=> Fixed _appManager/HardwareMissmatch channel name

io.openems.edge.battery.fenecon.home/src/io/openems/edge/battery/fenecon/home/BatteryFeneconHome.java, io.openems.edge.battery.fenecon.home/src/io/openems/edge/battery/fenecon/home/BatteryFeneconHomeImpl.java, io.openems.edge.goodwe/src/io/openems/edge/goodwe/common/AbstractGoodWe.java
Fixed a typo in the HW_AFE_COMMUNICATION_FAULT channel name. Since this a channel name, not sure if it is easy enough to be fixed and what potential external dependencies are.
Feel free to close this PR if a fix would be able to break external code.
=> Fixed HW_AFE_COMMUNICATION_FAULT channel name

.github/workflows/stale.yml
Add workflow, to keep Pull-Requests and Issues clean.
1. Automatically mark Issues as stale after 60 days of inactivity.
2. Automatically close them 7 days after being marked as stale.
=> Add workflow to mark and close old issues and PRs

io.openems.edge.simulator/src/io/openems/edge/simulator/ess/symmetric/reacting/Config.java, io.openems.edge.simulator/src/io/openems/edge/simulator/ess/symmetric/reacting/SimulatorEssSymmetricReactingImpl.java, io.openems.edge.simulator/test/io/openems/edge/simulator/ess/symmetric/reacting/MyConfig.java, io.openems.edge.simulator/test/io/openems/edge/simulator/ess/symmetric/reacting/SimulatorEssSymmetricReactingImplTest.java
Currently the dis/charge limit was based on the capacity. With this change it's configurable.
Testing: Executed `java -jar build/openems-edge.jar` and configured simulated ess with custom dis/charge limits and verified them via using the fixed state of charge controller
=> feat(simulated ess): allow configuration of dis/charge limit

io.openems.common/resources/templates/controller/$testSrcDir$/$basePackageDir$/MyConfig.java
The "import io.openems.edge.test.Config" caused an import not found error. After removing the import, it compiles fine.
=> Update MyConfig.java: removed import
